"use client";

// Pipeline copy, localized. Every supported language carries EVERY key — the
// `Copy` type on each language block makes a missing key a compile error, so no
// language can silently fall back to English. Kept separate from
// dictionaries.ts to avoid churn on that actively-developed file; can be folded
// in later. Voice: calm, plain, non-decisional — in every language.

import { useI18n } from "@/lib/i18n";
import type { Language } from "@/lib/dictionaries";

const en = {
  appTitle: "Your application",
  appSubtitle: "RealDoor prepares and checks your paperwork for affordable housing in Boston. It never decides eligibility.",
  getStarted: "Get started",
  step1: "Profile",
  step2: "Understand",
  step3: "Prepare",
  step1Info: "Upload & confirm",
  step2Info: "Income & rules",
  step3Info: "Check & export",
  stepLockedNote: "Finish the previous step first",
  back: "Back",
  next: "Next",
  continue: "Continue",

  statusLabel: "Status",
  incomeLabel: "Gross income",
  errorsLabel: "Errors",
  statusEmpty: "Not started",
  statusProfile: "Profile · in progress",
  statusUnderstand: "Understand · in progress",
  statusPrepare: "Prepare · in progress",
  statusReady: "Ready to review",
  statusNeeds: "Needs review",
  statusAwaiting: "{n} values need your confirmation",
  fieldsNeedReview: "Some fields need review",
  statusIssues: "Needs review · {n} to resolve",
  statusMissingDocs: "Ready to review · documents still missing",
  statusLocked: "Locked · ready to review",
  errorsMenuTitle: "What needs attention",
  errLowConfidence: "Low confidence — check this value",

  // Consistency warnings (Profile upload checks)
  wEyebrow: "Warnings",
  wTitle: "Consistency checks",
  wOpen: "Open",
  wUpload: "Upload",
  wNoFields: "No extracted fields for this document yet.",
  wAriaPanel: "Upload consistency warnings",
  wAriaReviewer: "Reviewer",
  wAriaProgress: "Review progress",
  wAriaStartParsing: "Start parsing",
  wParseFailed: "Parsing didn't complete. The document service couldn't be reached — your files stay on this device. Check your connection and press Start parsing again.",
  wMissingRequiredTitle: "{doc} missing",
  wMissingRequiredDetail: "Upload this required document before final review.",
  wTypeMismatchTitle: "Document type mismatch",
  wTypeMismatchDetail: "{slot} was parsed as {parsed}. Check that the uploaded file is in the right slot.",
  wLowDocTitle: "Low document confidence",
  wLowDocDetail: "{slot} classification is {pct}%. Check the document type before continuing.",
  wMissingFieldsTitle: "Missing extracted fields",
  wMissingFieldsDetail: "{slot}: {list}. Review or enter manually if needed.",
  wDupFileTitle: "Possible duplicate file",
  wDupFileDetail: "{n} uploads use the same file name: {name}.",
  wDupTypeTitle: "Possible duplicate document type",
  wDupTypeDetail: "{n} {doc} documents were uploaded. Check whether all are intended.",
  wNameMismatchTitle: "Applicant name mismatch",
  wNameMismatchDetail: "Different names detected: {names}. Check that all documents belong to the same file.",
  wExtractErrorTitle: "Parser could not extract this document",
  wExtractErrorOcr: "OCR is unavailable locally, so this scanned/rasterized document needs Tesseract or manual review.",
  wLowFieldsTitle: "Low confidence fields",
  wLowFieldsDetail: "{doc}: {list}.",
  wQuarantineTitle: "Untrusted instruction detected",
  wQuarantineDetail: "The parser quarantined adversarial or unrelated instruction text from this document.",
  wPayTotalTitle: "Pay stub total mismatch",
  wPayTotalDetail: "Gross pay does not match hours × rate ({hours} × {rate} ≈ {total}).",
  wNetOverTitle: "Net pay exceeds gross pay",
  wNetOverDetail: "Net pay should not be higher than gross pay. Check the extraction.",
  wPeriodOrderTitle: "Pay period dates look reversed",
  wPeriodOrderDetail: "Pay period start is after pay period end.",
  wEmploymentStaleTitle: "Employment letter may be stale",
  wEmploymentStaleDetail: "The document date is outside the 60-day currency window.",
  wGigTitle: "Gig income needs corroboration",
  wGigDetail: "Gig receipts are annualized, but should be reviewed against supporting evidence.",
  slotDescApplication: "Identity, household size, address, application date.",
  slotDescPayStub: "Gross pay, cadence, hours, rate, period dates.",
  slotDescEmployment: "Employer rate, schedule, document date.",
  slotDescBenefit: "If applicable: recurring benefit amount and frequency.",
  slotDescGig: "If applicable: monthly gross receipts and platform fees.",

  // Discover explorer (public LIHTC property records)
  dvTitle: "Properties",
  dvCount: "{n} public property records",
  dvFiltersAria: "Property filters",
  dvCity: "City",
  dvCityAll: "All cities",
  dvBedrooms: "Bedrooms",
  dvBedroomsAny: "Any bedrooms",
  dvBrStudio: "Studio",
  dvBr1: "1 bedroom",
  dvBr2: "2 bedrooms",
  dvBr3: "3 bedrooms",
  dvBr4: "4 bedrooms",
  dvNear: "Near",
  dvNearNone: "No location",
  dvWithin: "Within",
  dvAnyDistance: "Any distance",
  dvWithinMi: "Within {mi} mi",
  dvClear: "Clear filters",
  dvMapAria: "Map of public LIHTC property records",
  dvMapStyleAria: "Map style",
  dvMapStandard: "Map",
  dvMapSatellite: "Satellite",
  dvNoRecords: "No records match these filters.",
  dvDetailAria: "Selected property details",
  dvCloseDetail: "Close property details",
  dvPhotoAlt: "Property exterior",
  dvAvailabilityUnknown: "Availability unknown",
  dvLowIncomeUnits: "Low-income units",
  dvTotalUnits: "Total units",
  dvBedroomsRow: "Bedrooms",
  dvDistance: "Distance",
  dvYearPlaced: "Year placed",
  dvSource: "Source",
  dvHudSource: "HUD LIHTC public data",
  dvViewSource: "View source",
  dvCopyAddress: "Copy address",
  dvChooseLocation: "Choose a location",
  dvNotReported: "Not reported",
  dvSelectPrompt: "Select a property on the map to view public details.",
  dvMi: "{d} mi",
  viewerLabel: "Document viewer",
  zoomIn: "Zoom in",
  zoomOut: "Zoom out",
  zoomFit: "Fit width",
  pageOfTotal: "Page {n} of {total}",
  snapToField: "Snap to value",
  previewError: "The document preview could not be shown. Use the link below to open the original.",

  uploadTitle: "Upload your documents",
  uploadHint: "Drag PDFs here, or choose files — pay stubs, benefit or employment letters, your application summary.",
  chooseFiles: "Choose files",
  reading: "Reading your documents…",
  noDocs: "No documents yet. Upload one to begin.",
  checklistTitle: "Documents checklist",
  present: "Uploaded",
  missing: "Still missing",

  docApplication_summary: "Application summary",
  docPay_stub: "Pay stub",
  docEmployment_letter: "Employment letter",
  docBenefit_letter: "Benefit letter",
  docGig_statement: "Gig statement",
  docUnknown: "Document",

  reviewTitle: "Confirm your details",
  reviewHint: "Check each value against its source, then confirm it or type a correction. Only confirmed values are used later.",
  documentOf: "Document {n} of {total}",
  fieldOf: "Field {n} of {total}",
  confirm: "Confirm",
  correct: "Edit",
  saveCorrection: "Save",
  cancel: "Cancel",
  confidence: "Confidence",
  stRenterEntered: "Entered by you",
  parameterNotPresent: "Parameter not present",
  insertManually: "Insert manually",
  valueRequired: "Enter a value before saving.",
  errNegative: "Error: the amount cannot be negative.",
  dismiss: "Dismiss",
  stExtracted: "Needs your check",
  stConfirmed: "Confirmed",
  stCorrected: "Corrected",
  source: "Source",
  page: "Page {n}",
  openDocument: "Open original document",
  whyNeeded: "Why this is needed",
  fieldExplainFallback: "{field} — extracted from {doc}.",
  allConfirmed: "All values confirmed.",
  goNextDocument: "Proceed to next document",
  goUnderstand: "Proceed to next phase",

  quarantineTitle: "Quarantined text — ignored",
  quarantineHint:
    "This document contained instructions aimed at the assistant. RealDoor ignores embedded instructions; the text is shown only for transparency and is never used as data.",

  understandTitle: "Understand your income and the rules",
  incomeCalcTitle: "Annualized income",
  householdSize: "Household size",
  annualizedIncome: "Annualized gross income",
  incomeComposition: "Annual income composition",
  incomeCompositionTitle: "Annual income",
  incomeCompositionSubtitle: "composition",
  incomeChartEmpty: "Confirm an income value to build this chart.",
  incomeShare: "{pct}% of confirmed total",
  netPayChart: "Take-home pay",
  deductionsChart: "Taxes & deductions",
  threshold60: "FY2026 60% income limit",
  comparison: "Comparison",
  cmpBelow: "At or below the published limit",
  cmpAbove: "Above the published limit",
  cmpNone: "No frozen threshold for this household size",
  effective: "Effective",
  notDecision: "This compares your income to a published limit — it is not an eligibility decision.",
  confirmSizeNote: "Confirm the household size in Profile for an exact threshold.",
  formulaHead: "How this was calculated",
  sourcesHead: "Income sources",
  srcCorroborates: "corroborates the same source — not added",
  sampleQ1: "What is the 60% income limit for a household of four?",
  sampleQ2: "When do the FY2026 income limits take effect?",
  sampleQ3: "How is recurring income annualized?",
  sampleQ4: "What makes a file ready to review?",
  mathPerPeriod: "Per period",
  mathPeriodsYr: "Periods / year",
  mathCalc: "Calculation",
  mathPerYear: "Per year",
  mathTotal: "Total",
  srcPay: "Pay",
  srcBenefit: "Benefit",
  srcGig: "Gig receipts",
  freqWeekly: "weekly",
  freqBiweekly: "biweekly",
  freqSemimonthly: "semimonthly",
  freqMonthly: "monthly",
  freqAnnual: "annual",

  rulesTitle: "Ask about the rules",
  rulesHint: "Answers come only from the frozen rule corpus, each with its citation.",
  askPlaceholder: "e.g. What is the 60% limit for a household of four?",
  ask: "Ask",
  tryAsking: "Try asking",
  answerIntro: "From the rule corpus:",
  aiSources: "Sources",
  aiGuideLabel: "RealDoor guide",
  aiCurrentDocument: "Current document",
  aiOutcomeAnswered: "Answered",
  aiOutcomeRefused: "Refused",
  aiOutcomeAbstained: "Abstained",
  aiOutcomeNeedsConfirmation: "Needs confirmation",
  aiOutcomeOutOfScope: "Out of scope",
  authOfficialHud: "Official · HUD",
  authOfficialFederal: "Official · Federal",
  authChallenge: "Challenge convention",
  abstain:
    "I can only answer from the frozen rule corpus and didn't find a matching rule. Try asking about income limits, the effective date, annualizing income, or readiness.",
  refusal:
    "RealDoor can't tell you whether you qualify, or whether you'll be approved or denied — those remain human decisions. It only prepares and checks your paperwork and compares income to a published limit.",
  aiThinking: "Checking sources…",
  aiPrivacy:
    "AI privacy: only confirmed numeric values, statuses, and source references are sent — never your files, raw document text, name, address, or filename. Avoid typing personal details in the question.",
  aiFallback: "The live AI guide was unavailable, so RealDoor used its local frozen-rule fallback.",

  prepareTitle: "Prepare and finish",
  readinessTitle: "File readiness",
  verdictNote: "This describes the file's completeness and consistency — never eligibility.",
  reasonsTitle: "What to resolve",
  noReasons: "Everything checks out — the file is complete and consistent.",
  prepareIntro: "Correct anything marked in red, then save your receipt as a PDF.",
  rc_PAY_STUB_TOTAL_CONFLICT: "A pay stub's stated gross doesn't match its hourly rate × hours.",
  rc_GIG_INCOME_UNCORROBORATED: "Gig income is included but needs corroboration.",
  rc_EMPLOYMENT_LETTER_EXPIRED: "An employment letter is older than the 60-day currency window.",
  rc_UNCONFIRMED_FIELDS: "Some fields still need your confirmation.",
  rc_LOW_CONFIDENCE_FIELDS: "Some fields were extracted with low confidence.",
  rc_BENEFIT_LETTER_EXPIRED: "A benefit letter is older than the 60-day currency window.",
  rc_PAY_STUB_EXPIRED: "A pay stub is older than the 60-day currency window.",
  rc_GIG_STATEMENT_EXPIRED: "A gig statement is older than the 60-day currency window.",
  rc_EMPLOYMENT_RATE_CONFLICT: "The employer letter states a different hourly rate than the pay stub.",
  rc_MISSING_HOUSEHOLD_SIZE: "No documented household size — the frozen threshold table cannot be applied.",
  rc_MISSING_INCOME_EVIDENCE: "No documented recurring income evidence was found.",
  rc_NO_FROZEN_THRESHOLD: "The household size is outside the frozen 1–8 table; no frozen threshold exists.",
  rc_UNVERIFIED_INCOME_CLAIM: "A self-declared income amount has no supporting evidence and was not counted.",
  rcTitle_BENEFIT_LETTER_EXPIRED: "Benefit letter expired",
  rcTitle_PAY_STUB_EXPIRED: "Pay stub expired",
  rcTitle_GIG_STATEMENT_EXPIRED: "Gig statement expired",
  rcTitle_EMPLOYMENT_RATE_CONFLICT: "Hourly rate conflict",
  rcTitle_MISSING_HOUSEHOLD_SIZE: "Household size missing",
  rcTitle_MISSING_INCOME_EVIDENCE: "Income evidence missing",
  rcTitle_NO_FROZEN_THRESHOLD: "No frozen threshold",
  rcTitle_UNVERIFIED_INCOME_CLAIM: "Self-declared income unverified",
  rc_MISSING_REQUIRED_DOCUMENT: "A recommended document hasn't been uploaded yet.",
  rcTitle_PAY_STUB_TOTAL_CONFLICT: "Pay stub totals conflict",
  rcTitle_GIG_INCOME_UNCORROBORATED: "Gig income uncorroborated",
  rcTitle_EMPLOYMENT_LETTER_EXPIRED: "Employment letter expired",
  rcTitle_UNCONFIRMED_FIELDS: "Unconfirmed fields",
  rcTitle_LOW_CONFIDENCE_FIELDS: "Low-confidence fields",
  rcTitle_MISSING_REQUIRED_DOCUMENT: "Missing recommended document",
  editBtn: "Edit",
  downloadBtn: "Download packet",
  deleteBtn: "Delete session",
  deleteConfirm: "Delete everything in this session? Documents, extracted values, and this receipt will be removed.",
  deletedProof: "Session deleted. {docs} documents and {fields} values removed at {at}.",
  lockBtn: "Confirm — lock as ready to review",
  unlockBtn: "Unlock to edit",
  lockedNote: "Locked as ready to review. You can unlock to edit.",
  fieldsConfirmed: "{n} of {total} fields confirmed",

  receiptTitle: "Your readiness receipt",
  receiptPrint: "Save as PDF",
  rawShow: "View raw data",
  rawHide: "Hide raw data",
  sampleWord: "SAMPLE",
  sampleBanner:
    "This is a SAMPLE document generated from your session data. It is NOT an official form.",
  receiptKicker: "Affordable housing paperwork · Boston · SAMPLE",
  receiptDocTitle: "Application readiness receipt",
  receiptGenerated: "Generated {date}",
  receiptFileLabel: "File",
  receiptSecDocs: "Documents provided",
  receiptSecIncome: "Income calculation",
  receiptSecReadiness: "File readiness",
  receiptEditNote: "Corrections here update your whole file instantly.",
  invalidAmount: "Enter a non-negative number, like 1250.00.",
  receiptFooter:
    "RealDoor prepared this summary to help a human reviewer. It can't tell you whether you qualify — readiness describes the paperwork only. Download-only: this receipt is never transmitted.",
};

export type Copy = typeof en;

const es: Copy = {
  appTitle: "Tu solicitud",
  appSubtitle: "RealDoor prepara y revisa tus documentos para vivienda asequible en Boston. Nunca decide la elegibilidad.",
  getStarted: "Empezar",
  step1: "Perfil", step2: "Entender", step3: "Preparar",
  step1Info: "Subir y confirmar", step2Info: "Ingresos y reglas", step3Info: "Revisar y exportar",
  stepLockedNote: "Completa primero el paso anterior",
  back: "Atrás", next: "Siguiente", continue: "Continuar",
  statusLabel: "Estado", incomeLabel: "Ingreso bruto", errorsLabel: "Errores",
  statusEmpty: "Sin empezar",
  statusProfile: "Perfil · en curso",
  statusUnderstand: "Entender · en curso",
  statusPrepare: "Preparar · en curso",
  statusReady: "Listo para revisar", statusNeeds: "Necesita revisión",
  statusAwaiting: "{n} valores necesitan tu confirmación",
  fieldsNeedReview: "Algunos campos necesitan revisión",
  statusIssues: "Necesita revisión · {n} por resolver",
  statusMissingDocs: "Listo para revisar · aún faltan documentos",
  statusLocked: "Bloqueado · listo para revisar",
  errorsMenuTitle: "Qué necesita atención",
  errLowConfidence: "Confianza baja — revisa este valor",

  wEyebrow: "Avisos",
  wTitle: "Verificaciones de consistencia",
  wOpen: "Abrir",
  wUpload: "Subir",
  wNoFields: "Aún no hay valores extraídos de este documento.",
  wAriaPanel: "Avisos de consistencia de la carga",
  wAriaReviewer: "Revisor",
  wAriaProgress: "Progreso de la revisión",
  wAriaStartParsing: "Iniciar el análisis",
  wParseFailed: "El análisis no se completó. No se pudo contactar el servicio de documentos — sus archivos permanecen en este dispositivo. Compruebe su conexión y pulse Iniciar el análisis de nuevo.",
  wMissingRequiredTitle: "Falta {doc}",
  wMissingRequiredDetail: "Sube este documento obligatorio antes de la revisión final.",
  wTypeMismatchTitle: "El tipo de documento no coincide",
  wTypeMismatchDetail: "{slot} se analizó como {parsed}. Verifica que el archivo esté en el lugar correcto.",
  wLowDocTitle: "Confianza baja en el documento",
  wLowDocDetail: "La clasificación de {slot} es del {pct}%. Verifica el tipo de documento antes de continuar.",
  wMissingFieldsTitle: "Faltan valores extraídos",
  wMissingFieldsDetail: "{slot}: {list}. Revísalos o ingrésalos manualmente si hace falta.",
  wDupFileTitle: "Posible archivo duplicado",
  wDupFileDetail: "{n} cargas usan el mismo nombre de archivo: {name}.",
  wDupTypeTitle: "Posible tipo de documento duplicado",
  wDupTypeDetail: "Se subieron {n} documentos de tipo {doc}. Verifica que todos sean intencionales.",
  wNameMismatchTitle: "Los nombres no coinciden",
  wNameMismatchDetail: "Se detectaron nombres distintos: {names}. Verifica que todos los documentos pertenezcan al mismo expediente.",
  wExtractErrorTitle: "No se pudo extraer este documento",
  wExtractErrorOcr: "El OCR no está disponible localmente; este documento escaneado necesita Tesseract o revisión manual.",
  wLowFieldsTitle: "Valores con confianza baja",
  wLowFieldsDetail: "{doc}: {list}.",
  wQuarantineTitle: "Instrucción no confiable detectada",
  wQuarantineDetail: "El analizador puso en cuarentena texto de instrucciones adversarias o ajenas de este documento.",
  wPayTotalTitle: "El total del talón de pago no cuadra",
  wPayTotalDetail: "El pago bruto no coincide con horas × tarifa ({hours} × {rate} ≈ {total}).",
  wNetOverTitle: "El pago neto supera el bruto",
  wNetOverDetail: "El pago neto no debería ser mayor que el bruto. Revisa la extracción.",
  wPeriodOrderTitle: "Las fechas del período parecen invertidas",
  wPeriodOrderDetail: "El inicio del período de pago es posterior a su fin.",
  wEmploymentStaleTitle: "La carta de empleo podría estar vencida",
  wEmploymentStaleDetail: "La fecha del documento está fuera de la ventana de vigencia de 60 días.",
  wGigTitle: "El ingreso gig necesita corroboración",
  wGigDetail: "Los ingresos gig se anualizan, pero deben revisarse contra evidencia de respaldo.",
  slotDescApplication: "Identidad, tamaño del hogar, dirección, fecha de solicitud.",
  slotDescPayStub: "Pago bruto, frecuencia, horas, tarifa, fechas del período.",
  slotDescEmployment: "Tarifa del empleador, horario, fecha del documento.",
  slotDescBenefit: "Si aplica: monto y frecuencia del beneficio recurrente.",
  slotDescGig: "Si aplica: ingresos brutos mensuales y comisiones de la plataforma.",

  dvTitle: "Propiedades",
  dvCount: "{n} registros públicos de propiedades",
  dvFiltersAria: "Filtros de propiedades",
  dvCity: "Ciudad",
  dvCityAll: "Todas las ciudades",
  dvBedrooms: "Habitaciones",
  dvBedroomsAny: "Cualquier número",
  dvBrStudio: "Estudio",
  dvBr1: "1 habitación",
  dvBr2: "2 habitaciones",
  dvBr3: "3 habitaciones",
  dvBr4: "4 habitaciones",
  dvNear: "Cerca de",
  dvNearNone: "Sin ubicación",
  dvWithin: "Dentro de",
  dvAnyDistance: "Cualquier distancia",
  dvWithinMi: "A menos de {mi} mi",
  dvClear: "Borrar filtros",
  dvMapAria: "Mapa de registros públicos de propiedades LIHTC",
  dvMapStyleAria: "Estilo del mapa",
  dvMapStandard: "Mapa",
  dvMapSatellite: "Satélite",
  dvNoRecords: "Ningún registro coincide con estos filtros.",
  dvDetailAria: "Detalles de la propiedad seleccionada",
  dvCloseDetail: "Cerrar los detalles de la propiedad",
  dvPhotoAlt: "Exterior de la propiedad",
  dvAvailabilityUnknown: "Disponibilidad desconocida",
  dvLowIncomeUnits: "Unidades de ingresos bajos",
  dvTotalUnits: "Unidades totales",
  dvBedroomsRow: "Habitaciones",
  dvDistance: "Distancia",
  dvYearPlaced: "Año de puesta en servicio",
  dvSource: "Fuente",
  dvHudSource: "Datos públicos LIHTC de HUD",
  dvViewSource: "Ver fuente",
  dvCopyAddress: "Copiar dirección",
  dvChooseLocation: "Elige una ubicación",
  dvNotReported: "No informado",
  dvSelectPrompt: "Selecciona una propiedad en el mapa para ver los datos públicos.",
  dvMi: "{d} mi",
  viewerLabel: "Visor de documentos",
  zoomIn: "Acercar", zoomOut: "Alejar", zoomFit: "Ajustar al ancho",
  pageOfTotal: "Página {n} de {total}", snapToField: "Ir al valor",
  previewError: "No se pudo mostrar la vista previa. Usa el enlace inferior para abrir el documento original.",
  uploadTitle: "Sube tus documentos",
  uploadHint:
    "Arrastra tus PDF aquí o elige archivos — talones de pago, cartas de beneficios o de empleo, tu resumen de solicitud.",
  chooseFiles: "Elegir archivos", reading: "Leyendo tus documentos…",
  noDocs: "Aún no hay documentos. Sube uno para empezar.",
  checklistTitle: "Lista de documentos", present: "Subido", missing: "Aún falta",
  docApplication_summary: "Resumen de solicitud",
  docPay_stub: "Talón de pago",
  docEmployment_letter: "Carta de empleo",
  docBenefit_letter: "Carta de beneficios",
  docGig_statement: "Estado de cuenta gig",
  docUnknown: "Documento",
  reviewTitle: "Confirma tus datos",
  reviewHint:
    "Compara cada valor con su fuente y luego confírmalo o escribe una corrección. Solo los valores confirmados se usan después.",
  documentOf: "Documento {n} de {total}",
  fieldOf: "Campo {n} de {total}",
  confirm: "Confirmar", correct: "Editar", saveCorrection: "Guardar",
  cancel: "Cancelar", confidence: "Confianza",
  stRenterEntered: "Ingresado por ti",
  parameterNotPresent: "Parámetro no presente",
  insertManually: "Ingresar manualmente",
  valueRequired: "Ingresa un valor antes de guardar.",
  errNegative: "Error: el importe no puede ser negativo.",
  dismiss: "Cerrar",
  stExtracted: "Requiere tu revisión", stConfirmed: "Confirmado", stCorrected: "Corregido",
  source: "Fuente",
  page: "Página {n}",
  openDocument: "Abrir el documento original",
  whyNeeded: "Por qué se necesita",
  fieldExplainFallback: "{field} — extraído de {doc}.",
  allConfirmed: "Todos los valores confirmados.",
  goNextDocument: "Pasar al siguiente documento",
  goUnderstand: "Pasar a la siguiente fase",
  quarantineTitle: "Texto en cuarentena — ignorado",
  quarantineHint:
    "Este documento contenía instrucciones dirigidas al asistente. RealDoor ignora las instrucciones incrustadas; el texto se muestra solo por transparencia y nunca se usa como datos.",
  understandTitle: "Entiende tus ingresos y las reglas",
  incomeCalcTitle: "Ingreso anualizado",
  householdSize: "Tamaño del hogar",
  annualizedIncome: "Ingreso bruto anualizado",
  incomeComposition: "Composición del ingreso anual",
  incomeCompositionTitle: "Ingreso anual",
  incomeCompositionSubtitle: "composición",
  incomeChartEmpty: "Confirma un valor de ingreso para crear este gráfico.",
  incomeShare: "{pct}% del total confirmado",
  netPayChart: "Pago neto",
  deductionsChart: "Impuestos y deducciones",
  srcCorroborates: "corrobora la misma fuente — no se suma",
  sampleQ1: "¿Cuál es el límite de ingresos del 60% para un hogar de cuatro?",
  sampleQ2: "¿Cuándo entran en vigor los límites de ingresos del FY2026?",
  sampleQ3: "¿Cómo se anualizan los ingresos recurrentes?",
  sampleQ4: "¿Qué hace que un expediente esté listo para revisar?",
  mathPerPeriod: "Por período",
  mathPeriodsYr: "Períodos al año",
  mathCalc: "Cálculo",
  mathPerYear: "Al año",
  mathTotal: "Total",
  srcPay: "Salario",
  srcBenefit: "Beneficio",
  srcGig: "Ingresos gig",
  aiThinking: "Consultando las fuentes…",
  aiPrivacy:
    "Privacidad de la IA: solo se envían valores numéricos confirmados, estados y referencias de fuente — nunca tus archivos, el texto de los documentos, tu nombre, dirección ni nombres de archivo. Evita escribir datos personales en la pregunta.",
  aiFallback: "El guía de IA en vivo no estaba disponible; RealDoor usó su respaldo local de reglas congeladas.",
  freqWeekly: "semanal", freqBiweekly: "cada dos semanas", freqSemimonthly: "dos veces al mes",
  freqMonthly: "mensual", freqAnnual: "anual",
  threshold60: "Límite de ingresos del 60% (FY2026)", comparison: "Comparación",
  cmpBelow: "Igual o por debajo del límite", cmpAbove: "Por encima del límite",
  cmpNone: "No hay límite congelado para este tamaño de hogar",
  effective: "Vigente desde",
  notDecision: "Esto compara tus ingresos con un límite publicado — no es una decisión de elegibilidad.",
  confirmSizeNote: "Confirma el tamaño del hogar en Perfil para un límite exacto.",
  formulaHead: "Cómo se calculó",
  sourcesHead: "Fuentes de ingresos",
  rulesTitle: "Pregunta sobre las reglas",
  rulesHint: "Las respuestas provienen solo del corpus de reglas congelado, cada una con su cita.",
  askPlaceholder: "p. ej. ¿Cuál es el límite del 60% para un hogar de cuatro?",
  ask: "Preguntar",
  tryAsking: "Prueba preguntar",
  answerIntro: "Del corpus de reglas:",
  aiSources: "Fuentes",
  aiGuideLabel: "Guía de RealDoor",
  aiCurrentDocument: "Documento actual",
  aiOutcomeAnswered: "Respondido",
  aiOutcomeRefused: "Rehusado",
  aiOutcomeAbstained: "Se abstuvo",
  aiOutcomeNeedsConfirmation: "Necesita confirmación",
  aiOutcomeOutOfScope: "Fuera de alcance",
  authOfficialHud: "Oficial · HUD",
  authOfficialFederal: "Oficial · Federal",
  authChallenge: "Convención del reto",
  abstain:
    "Solo puedo responder desde el corpus de reglas congelado y no encontré una regla que coincida. Prueba preguntar sobre los límites de ingresos, la fecha de vigencia, la anualización de ingresos o la preparación del expediente.",
  refusal: "RealDoor no puede decirte si cumples los requisitos, ni si serás aprobado o rechazado — esas son decisiones humanas. Solo prepara y revisa tus documentos y compara los ingresos con un límite publicado.",
  prepareTitle: "Prepara y finaliza", readinessTitle: "Preparación del expediente",
  verdictNote: "Describe qué tan completo y coherente está el expediente — nunca la elegibilidad.",
  reasonsTitle: "Qué resolver",
  noReasons: "Todo está en orden — el expediente está completo y es coherente.",
  prepareIntro:
    "Revisa tu recibo abajo — corrige lo marcado en rojo y luego guárdalo como PDF o descarga el paquete de datos.",
  rcTitle_PAY_STUB_TOTAL_CONFLICT: "Conflicto en los totales del recibo de pago",
  rcTitle_GIG_INCOME_UNCORROBORATED: "Ingresos por plataforma sin corroborar",
  rcTitle_EMPLOYMENT_LETTER_EXPIRED: "Carta de empleo vencida",
  rcTitle_UNCONFIRMED_FIELDS: "Campos sin confirmar",
  rcTitle_LOW_CONFIDENCE_FIELDS: "Campos con baja confianza",
  rcTitle_MISSING_REQUIRED_DOCUMENT: "Falta un documento recomendado",
  rc_PAY_STUB_TOTAL_CONFLICT: "El bruto declarado de un talón de pago no coincide con su tarifa por hora × horas.",
  rc_GIG_INCOME_UNCORROBORATED: "Los ingresos gig están incluidos pero necesitan corroboración.",
  rc_EMPLOYMENT_LETTER_EXPIRED: "Una carta de empleo es más antigua que la ventana de vigencia de 60 días.",
  rc_UNCONFIRMED_FIELDS: "Algunos campos aún necesitan tu confirmación.",
  rc_LOW_CONFIDENCE_FIELDS: "Algunos campos se extrajeron con confianza baja.",
  rc_BENEFIT_LETTER_EXPIRED: "Una carta de beneficios supera la ventana de vigencia de 60 días.",
  rc_PAY_STUB_EXPIRED: "Un recibo de pago supera la ventana de vigencia de 60 días.",
  rc_GIG_STATEMENT_EXPIRED: "Un estado de ingresos gig supera la ventana de vigencia de 60 días.",
  rc_EMPLOYMENT_RATE_CONFLICT: "La carta del empleador indica una tarifa por hora distinta a la del recibo de pago.",
  rc_MISSING_HOUSEHOLD_SIZE: "No hay tamaño del hogar documentado — no se puede aplicar la tabla de límites congelada.",
  rc_MISSING_INCOME_EVIDENCE: "No se encontró evidencia documentada de ingresos recurrentes.",
  rc_NO_FROZEN_THRESHOLD: "El tamaño del hogar está fuera de la tabla congelada de 1–8; no existe límite congelado.",
  rc_UNVERIFIED_INCOME_CLAIM: "Un ingreso autodeclarado no tiene evidencia de respaldo y no se contó.",
  rcTitle_BENEFIT_LETTER_EXPIRED: "Carta de beneficios vencida",
  rcTitle_PAY_STUB_EXPIRED: "Recibo de pago vencido",
  rcTitle_GIG_STATEMENT_EXPIRED: "Estado gig vencido",
  rcTitle_EMPLOYMENT_RATE_CONFLICT: "Conflicto de tarifa por hora",
  rcTitle_MISSING_HOUSEHOLD_SIZE: "Falta el tamaño del hogar",
  rcTitle_MISSING_INCOME_EVIDENCE: "Falta evidencia de ingresos",
  rcTitle_NO_FROZEN_THRESHOLD: "Sin límite congelado",
  rcTitle_UNVERIFIED_INCOME_CLAIM: "Ingreso autodeclarado sin verificar",
  rc_MISSING_REQUIRED_DOCUMENT: "Un documento recomendado aún no se ha subido.",
  editBtn: "Editar", downloadBtn: "Descargar paquete",
  deleteBtn: "Borrar sesión", lockBtn: "Confirmar — marcar como listo para revisar",
  unlockBtn: "Desbloquear para editar",
  lockedNote: "Bloqueado como listo para revisar. Puedes desbloquear para editar.",
  deleteConfirm: "¿Borrar todo en esta sesión? Se eliminarán los documentos, los valores extraídos y este recibo.",
  deletedProof: "Sesión borrada. {docs} documentos y {fields} valores eliminados el {at}.",
  fieldsConfirmed: "{n} de {total} campos confirmados",
  receiptTitle: "Tu recibo de preparación",
  receiptPrint: "Guardar como PDF",
  rawShow: "Ver datos sin procesar", rawHide: "Ocultar datos sin procesar",
  sampleWord: "MUESTRA",
  sampleBanner:
    "Este es un documento de MUESTRA generado con los datos de tu sesión. NO es un formulario oficial.",
  receiptKicker: "Documentos de vivienda asequible · Boston · MUESTRA",
  receiptDocTitle: "Recibo de preparación de la solicitud",
  receiptGenerated: "Generado el {date}",
  receiptFileLabel: "Expediente",
  receiptSecDocs: "Documentos entregados",
  receiptSecIncome: "Cálculo de ingresos",
  receiptSecReadiness: "Preparación del expediente",
  receiptEditNote: "Las correcciones aquí actualizan todo tu expediente al instante.",
  invalidAmount: "Introduce un número no negativo, como 1250.00.",
  receiptFooter:
    "RealDoor preparó este resumen para ayudar a un revisor humano. No puede decirte si cumples los requisitos — la preparación describe solo los documentos. Solo descarga: este recibo nunca se transmite.",
};

const zh: Copy = {
  appTitle: "您的申请",
  appSubtitle: "RealDoor 帮您准备并核对波士顿可负担住房的申请材料，绝不判定资格。",
  getStarted: "开始",
  step1: "个人资料", step2: "了解", step3: "准备",
  step1Info: "上传并确认", step2Info: "收入与规则", step3Info: "检查并导出",
  stepLockedNote: "请先完成上一步",
  back: "返回", next: "下一步", continue: "继续",
  statusLabel: "状态", incomeLabel: "总收入", errorsLabel: "错误",
  statusEmpty: "未开始",
  statusProfile: "个人资料 · 进行中",
  statusUnderstand: "了解 · 进行中",
  statusPrepare: "准备 · 进行中",
  statusReady: "可供审核", statusNeeds: "需要复核",
  statusAwaiting: "{n} 项信息待您确认",
  fieldsNeedReview: "部分字段需要审核",
  statusIssues: "需要复核 · {n} 项待解决",
  statusMissingDocs: "可供审核 · 仍缺少文件",
  statusLocked: "已锁定 · 可供审核",
  errorsMenuTitle: "需要处理的事项",
  errLowConfidence: "置信度低——请核对此值",

  wEyebrow: "提醒",
  wTitle: "一致性检查",
  wOpen: "查看",
  wUpload: "上传",
  wNoFields: "此文件尚未提取出任何字段。",
  wAriaPanel: "上传一致性提醒",
  wAriaReviewer: "审核器",
  wAriaProgress: "审核进度",
  wAriaStartParsing: "开始解析",
  wParseFailed: "解析未完成。无法连接文档服务——您的文件仍保留在本设备上。请检查网络连接后再次点击“开始解析”。",
  wMissingRequiredTitle: "缺少{doc}",
  wMissingRequiredDetail: "请在最终审核前上传此必需文件。",
  wTypeMismatchTitle: "文件类型不匹配",
  wTypeMismatchDetail: "{slot}被解析为{parsed}。请确认文件放在了正确的位置。",
  wLowDocTitle: "文件置信度低",
  wLowDocDetail: "{slot}的分类置信度为 {pct}%。请在继续前核对文件类型。",
  wMissingFieldsTitle: "缺少提取字段",
  wMissingFieldsDetail: "{slot}：{list}。如有需要请核对或手动输入。",
  wDupFileTitle: "可能存在重复文件",
  wDupFileDetail: "{n} 个上传使用了相同的文件名：{name}。",
  wDupTypeTitle: "可能存在重复的文件类型",
  wDupTypeDetail: "上传了 {n} 份{doc}。请确认均为有意上传。",
  wNameMismatchTitle: "申请人姓名不一致",
  wNameMismatchDetail: "检测到不同的姓名：{names}。请确认所有文件属于同一份申请。",
  wExtractErrorTitle: "无法解析此文件",
  wExtractErrorOcr: "本地无法使用 OCR，此扫描/栅格化文件需要 Tesseract 或人工核对。",
  wLowFieldsTitle: "置信度低的字段",
  wLowFieldsDetail: "{doc}：{list}。",
  wQuarantineTitle: "检测到不可信指令",
  wQuarantineDetail: "解析器已隔离此文件中的对抗性或无关指令文本。",
  wPayTotalTitle: "工资单总额不符",
  wPayTotalDetail: "工资总额与时数 × 时薪不符（{hours} × {rate} ≈ {total}）。",
  wNetOverTitle: "实发工资超过应发工资",
  wNetOverDetail: "实发工资不应高于应发工资。请核对提取结果。",
  wPeriodOrderTitle: "工资周期日期疑似颠倒",
  wPeriodOrderDetail: "工资周期的开始日期晚于结束日期。",
  wEmploymentStaleTitle: "雇佣证明信可能已过期",
  wEmploymentStaleDetail: "文件日期超出 60 天有效窗口。",
  wGigTitle: "零工收入需要佐证",
  wGigDetail: "零工收入已按年化计算，但仍应对照支持性证据核对。",
  slotDescApplication: "身份、家庭人数、地址、申请日期。",
  slotDescPayStub: "工资总额、发放频率、时数、时薪、周期日期。",
  slotDescEmployment: "雇主时薪、工作时间安排、文件日期。",
  slotDescBenefit: "如适用：经常性补助金额与频率。",
  slotDescGig: "如适用：每月总收入与平台费用。",

  dvTitle: "房源",
  dvCount: "{n} 条公开房产记录",
  dvFiltersAria: "房产筛选条件",
  dvCity: "城市",
  dvCityAll: "所有城市",
  dvBedrooms: "卧室",
  dvBedroomsAny: "不限卧室",
  dvBrStudio: "单间",
  dvBr1: "1 室",
  dvBr2: "2 室",
  dvBr3: "3 室",
  dvBr4: "4 室",
  dvNear: "附近",
  dvNearNone: "不限地点",
  dvWithin: "范围",
  dvAnyDistance: "不限距离",
  dvWithinMi: "{mi} 英里内",
  dvClear: "清除筛选",
  dvMapAria: "LIHTC 公开房产记录地图",
  dvMapStyleAria: "地图样式",
  dvMapStandard: "地图",
  dvMapSatellite: "卫星",
  dvNoRecords: "没有符合这些筛选条件的记录。",
  dvDetailAria: "所选房产详情",
  dvCloseDetail: "关闭房产详情",
  dvPhotoAlt: "房产外观",
  dvAvailabilityUnknown: "空置情况未知",
  dvLowIncomeUnits: "低收入单元",
  dvTotalUnits: "单元总数",
  dvBedroomsRow: "卧室",
  dvDistance: "距离",
  dvYearPlaced: "投入使用年份",
  dvSource: "来源",
  dvHudSource: "HUD LIHTC 公开数据",
  dvViewSource: "查看来源",
  dvCopyAddress: "复制地址",
  dvChooseLocation: "请选择一个地点",
  dvNotReported: "未报告",
  dvSelectPrompt: "在地图上选择一处房产以查看公开信息。",
  dvMi: "{d} 英里",
  viewerLabel: "文件查看器",
  zoomIn: "放大", zoomOut: "缩小", zoomFit: "适合宽度",
  pageOfTotal: "第 {n} 页，共 {total} 页", snapToField: "定位到该值",
  previewError: "无法显示文件预览。请使用下方链接打开原始文件。",
  uploadTitle: "上传您的文件",
  uploadHint: "将 PDF 拖到此处或选择文件——工资单、福利或在职证明信、您的申请摘要。",
  chooseFiles: "选择文件", reading: "正在读取您的文件…",
  noDocs: "还没有文件。上传一份即可开始。",
  checklistTitle: "文件清单", present: "已上传", missing: "仍缺少",
  docApplication_summary: "申请摘要",
  docPay_stub: "工资单",
  docEmployment_letter: "在职证明信",
  docBenefit_letter: "福利信",
  docGig_statement: "零工对账单",
  docUnknown: "文件",
  reviewTitle: "确认您的信息",
  reviewHint: "将每个数值与其来源核对，然后确认或输入更正。之后只使用已确认的数值。",
  documentOf: "文件 {n}/{total}",
  fieldOf: "第 {n} 项，共 {total} 项",
  confirm: "确认", correct: "编辑", saveCorrection: "保存",
  cancel: "取消", confidence: "置信度",
  stRenterEntered: "由您输入",
  parameterNotPresent: "参数不存在",
  insertManually: "手动输入",
  valueRequired: "请先输入一个值再保存。",
  errNegative: "错误：金额不能为负数。",
  dismiss: "关闭",
  stExtracted: "待您核对", stConfirmed: "已确认", stCorrected: "已更正",
  source: "来源",
  page: "第 {n} 页",
  openDocument: "打开原始文件",
  whyNeeded: "为何需要",
  fieldExplainFallback: "{field}——提取自{doc}。",
  allConfirmed: "所有数值均已确认。",
  goNextDocument: "继续至下一份文件",
  goUnderstand: "进入下一阶段",
  quarantineTitle: "已隔离的文字——已忽略",
  quarantineHint:
    "此文件包含针对助手的指令。RealDoor 会忽略嵌入的指令；文字仅为透明起见显示，绝不会用作数据。",
  understandTitle: "了解您的收入与规则",
  incomeCalcTitle: "年化收入",
  householdSize: "家庭人数",
  annualizedIncome: "年化总收入",
  incomeComposition: "年收入构成",
  incomeCompositionTitle: "年收入",
  incomeCompositionSubtitle: "构成",
  incomeChartEmpty: "确认一项收入值后即可生成此图。",
  incomeShare: "占已确认总额的 {pct}%",
  netPayChart: "实得工资",
  deductionsChart: "税费与扣除",
  srcCorroborates: "佐证同一来源——不重复计入",
  sampleQ1: "四口之家的 60% 收入上限是多少？",
  sampleQ2: "2026 财年收入上限何时生效？",
  sampleQ3: "经常性收入如何年化？",
  sampleQ4: "什么情况下材料可供审核？",
  mathPerPeriod: "每期",
  mathPeriodsYr: "每年期数",
  mathCalc: "计算",
  mathPerYear: "每年",
  mathTotal: "合计",
  srcPay: "工资",
  srcBenefit: "福利",
  srcGig: "零工收入",
  aiThinking: "正在核对来源…",
  aiPrivacy:
    "AI 隐私：仅发送已确认的数值、状态和来源引用——绝不发送您的文件、文档原文、姓名、地址或文件名。请避免在问题中输入个人信息。",
  aiFallback: "在线 AI 助手不可用，RealDoor 已使用本地冻结规则备用方案。",
  freqWeekly: "每周", freqBiweekly: "每两周", freqSemimonthly: "每半月",
  freqMonthly: "每月", freqAnnual: "每年",
  threshold60: "2026 财年 60% 收入上限", comparison: "比较",
  cmpBelow: "等于或低于上限", cmpAbove: "高于上限",
  cmpNone: "此家庭人数没有冻结的上限",
  effective: "生效日期",
  notDecision: "这是将您的收入与公布上限比较——并非资格判定。",
  confirmSizeNote: "请在“个人资料”中确认家庭人数以获得准确上限。",
  formulaHead: "计算方式",
  sourcesHead: "收入来源",
  rulesTitle: "咨询相关规则",
  rulesHint: "回答仅来自冻结的规则库，每条均附引用。",
  askPlaceholder: "例如：四口之家的 60% 上限是多少？",
  ask: "提问",
  tryAsking: "试试提问",
  answerIntro: "来自规则库：",
  aiSources: "来源",
  aiGuideLabel: "RealDoor 指南",
  aiCurrentDocument: "当前文件",
  aiOutcomeAnswered: "已回答",
  aiOutcomeRefused: "已拒答",
  aiOutcomeAbstained: "未作答",
  aiOutcomeNeedsConfirmation: "需要确认",
  aiOutcomeOutOfScope: "超出范围",
  authOfficialHud: "官方 · HUD",
  authOfficialFederal: "官方 · 联邦",
  authChallenge: "挑战赛约定",
  abstain:
    "我只能根据冻结的规则库回答，未找到匹配的规则。可以试试询问收入上限、生效日期、收入年化或材料就绪情况。",
  refusal: "RealDoor 无法告诉您是否符合资格，也无法判定批准或拒绝——这些属于人工决定。它只帮您准备和核对材料，并将收入与公布的上限进行比较。",
  prepareTitle: "准备并完成", readinessTitle: "材料就绪情况",
  verdictNote: "这说明材料的完整性与一致性——绝不涉及资格。",
  reasonsTitle: "需要解决的事项",
  noReasons: "一切正常——材料完整且一致。",
  prepareIntro: "请检查下方的回执——更正标为红色的内容，然后将其保存为 PDF 或下载数据包。",
  rcTitle_PAY_STUB_TOTAL_CONFLICT: "工资单总额不符",
  rcTitle_GIG_INCOME_UNCORROBORATED: "零工收入未经佐证",
  rcTitle_EMPLOYMENT_LETTER_EXPIRED: "雇佣证明信已过期",
  rcTitle_UNCONFIRMED_FIELDS: "字段未确认",
  rcTitle_LOW_CONFIDENCE_FIELDS: "字段置信度低",
  rcTitle_MISSING_REQUIRED_DOCUMENT: "缺少建议文件",
  rc_PAY_STUB_TOTAL_CONFLICT: "一张工资单标注的总额与其时薪 × 工时不符。",
  rc_GIG_INCOME_UNCORROBORATED: "零工收入已计入，但需要佐证。",
  rc_EMPLOYMENT_LETTER_EXPIRED: "一封在职证明信超出了 60 天有效期窗口。",
  rc_UNCONFIRMED_FIELDS: "部分信息仍需您确认。",
  rc_LOW_CONFIDENCE_FIELDS: "部分信息提取时置信度较低。",
  rc_BENEFIT_LETTER_EXPIRED: "一封福利证明信超出了 60 天有效期窗口。",
  rc_PAY_STUB_EXPIRED: "一张工资单超出了 60 天有效期窗口。",
  rc_GIG_STATEMENT_EXPIRED: "一份零工收入单超出了 60 天有效期窗口。",
  rc_EMPLOYMENT_RATE_CONFLICT: "雇主信中注明的时薪与工资单不一致。",
  rc_MISSING_HOUSEHOLD_SIZE: "没有记录在案的家庭人数——无法应用冻结的上限表。",
  rc_MISSING_INCOME_EVIDENCE: "未找到记录在案的经常性收入证明。",
  rc_NO_FROZEN_THRESHOLD: "家庭人数超出冻结的 1–8 人表；不存在冻结上限。",
  rc_UNVERIFIED_INCOME_CLAIM: "自行申报的收入金额没有佐证材料，未被计入。",
  rcTitle_BENEFIT_LETTER_EXPIRED: "福利证明信已过期",
  rcTitle_PAY_STUB_EXPIRED: "工资单已过期",
  rcTitle_GIG_STATEMENT_EXPIRED: "零工收入单已过期",
  rcTitle_EMPLOYMENT_RATE_CONFLICT: "时薪不一致",
  rcTitle_MISSING_HOUSEHOLD_SIZE: "缺少家庭人数",
  rcTitle_MISSING_INCOME_EVIDENCE: "缺少收入证明",
  rcTitle_NO_FROZEN_THRESHOLD: "无冻结上限",
  rcTitle_UNVERIFIED_INCOME_CLAIM: "自报收入未经核实",
  rc_MISSING_REQUIRED_DOCUMENT: "有一份建议提供的文件尚未上传。",
  editBtn: "编辑", downloadBtn: "下载材料包",
  deleteBtn: "删除会话", lockBtn: "确认——标记为可供审核",
  unlockBtn: "解锁以编辑",
  lockedNote: "已锁定为可供审核。您可以解锁进行编辑。",
  deleteConfirm: "删除本会话中的所有内容？文件、提取的数值和此回执都将被移除。",
  deletedProof: "会话已删除。已于 {at} 移除 {docs} 份文件和 {fields} 项数值。",
  fieldsConfirmed: "已确认 {n}/{total} 项",
  receiptTitle: "您的就绪回执",
  receiptPrint: "保存为 PDF",
  rawShow: "查看原始数据", rawHide: "隐藏原始数据",
  sampleWord: "样本",
  sampleBanner: "这是根据您的会话数据生成的样本文件。它不是官方表格。",
  receiptKicker: "可负担住房材料 · 波士顿 · 样本",
  receiptDocTitle: "申请就绪回执",
  receiptGenerated: "生成于 {date}",
  receiptFileLabel: "档案",
  receiptSecDocs: "已提供的文件",
  receiptSecIncome: "收入计算",
  receiptSecReadiness: "材料就绪情况",
  receiptEditNote: "在此处的更正会立即更新您的整个档案。",
  invalidAmount: "请输入非负数字，例如 1250.00。",
  receiptFooter:
    "RealDoor 准备本摘要以协助人工审核。它无法告诉您是否符合资格——就绪仅描述材料本身。仅供下载：此回执绝不会被传送。",
};

const tl: Copy = {
  appTitle: "Ang iyong aplikasyon",
  appSubtitle: "Inihahanda at sinusuri ng RealDoor ang iyong mga papeles para sa abot-kayang pabahay sa Boston. Hindi ito nagpapasya ng eligibility.",
  getStarted: "Magsimula",
  step1: "Profile", step2: "Unawain", step3: "Maghanda",
  step1Info: "I-upload at kumpirmahin", step2Info: "Kita at patakaran", step3Info: "Suriin at i-export",
  stepLockedNote: "Tapusin muna ang naunang hakbang",
  back: "Bumalik", next: "Susunod", continue: "Magpatuloy",
  statusLabel: "Katayuan", incomeLabel: "Kabuuang kita", errorsLabel: "Mga error",
  statusEmpty: "Hindi pa nagsisimula",
  statusProfile: "Profile · isinasagawa",
  statusUnderstand: "Unawain · isinasagawa",
  statusPrepare: "Maghanda · isinasagawa",
  statusReady: "Handa nang suriin", statusNeeds: "Kailangang suriin",
  statusAwaiting: "{n} na halaga ang kailangang kumpirmahin",
  fieldsNeedReview: "May mga field na kailangang suriin",
  statusIssues: "Kailangang suriin · {n} ang dapat ayusin",
  statusMissingDocs: "Handa nang suriin · may kulang pang dokumento",
  statusLocked: "Naka-lock · handa nang suriin",
  errorsMenuTitle: "Ano ang kailangang asikasuhin",
  errLowConfidence: "Mababa ang kumpiyansa — suriin ang halagang ito",

  wEyebrow: "Mga babala",
  wTitle: "Mga pagsusuri sa pagkakapare-pareho",
  wOpen: "Buksan",
  wUpload: "I-upload",
  wNoFields: "Wala pang na-extract na field mula sa dokumentong ito.",
  wAriaPanel: "Mga babala sa pagkakapare-pareho ng upload",
  wAriaReviewer: "Tagasuri",
  wAriaProgress: "Progreso ng pagsusuri",
  wAriaStartParsing: "Simulan ang pag-parse",
  wParseFailed: "Hindi natapos ang pag-parse. Hindi ma-abot ang serbisyo ng dokumento — nananatili ang inyong mga file sa device na ito. Suriin ang koneksyon at pindutin muli ang Simulan ang pag-parse.",
  wMissingRequiredTitle: "Kulang ang {doc}",
  wMissingRequiredDetail: "I-upload ang kinakailangang dokumentong ito bago ang huling pagsusuri.",
  wTypeMismatchTitle: "Hindi tugma ang uri ng dokumento",
  wTypeMismatchDetail: "Ang {slot} ay na-parse bilang {parsed}. Tiyaking nasa tamang puwesto ang na-upload na file.",
  wLowDocTitle: "Mababa ang kumpiyansa sa dokumento",
  wLowDocDetail: "Ang klasipikasyon ng {slot} ay {pct}%. Suriin ang uri ng dokumento bago magpatuloy.",
  wMissingFieldsTitle: "May kulang na na-extract na field",
  wMissingFieldsDetail: "{slot}: {list}. Suriin o ilagay nang mano-mano kung kailangan.",
  wDupFileTitle: "Posibleng dobleng file",
  wDupFileDetail: "{n} upload ang gumagamit ng parehong pangalan ng file: {name}.",
  wDupTypeTitle: "Posibleng dobleng uri ng dokumento",
  wDupTypeDetail: "{n} dokumentong {doc} ang na-upload. Tiyaking sadya ang lahat.",
  wNameMismatchTitle: "Hindi tugma ang pangalan ng aplikante",
  wNameMismatchDetail: "May iba't ibang pangalan na natukoy: {names}. Tiyaking iisang file ang pinagmulan ng lahat ng dokumento.",
  wExtractErrorTitle: "Hindi ma-extract ng parser ang dokumentong ito",
  wExtractErrorOcr: "Hindi available ang OCR nang lokal, kaya ang na-scan na dokumentong ito ay nangangailangan ng Tesseract o manwal na pagsusuri.",
  wLowFieldsTitle: "Mga field na mababa ang kumpiyansa",
  wLowFieldsDetail: "{doc}: {list}.",
  wQuarantineTitle: "May natukoy na hindi mapagkakatiwalaang utos",
  wQuarantineDetail: "In-quarantine ng parser ang adversarial o hindi kaugnay na teksto ng utos mula sa dokumentong ito.",
  wPayTotalTitle: "Hindi tugma ang kabuuan ng pay stub",
  wPayTotalDetail: "Hindi tugma ang gross pay sa oras × rate ({hours} × {rate} ≈ {total}).",
  wNetOverTitle: "Mas mataas ang net pay kaysa gross pay",
  wNetOverDetail: "Hindi dapat mas mataas ang net pay kaysa gross pay. Suriin ang extraction.",
  wPeriodOrderTitle: "Mukhang baligtad ang mga petsa ng pay period",
  wPeriodOrderDetail: "Ang simula ng pay period ay pagkatapos ng katapusan nito.",
  wEmploymentStaleTitle: "Maaaring luma na ang employment letter",
  wEmploymentStaleDetail: "Ang petsa ng dokumento ay lampas sa 60-araw na saklaw ng bisa.",
  wGigTitle: "Kailangan ng karagdagang patunay ang kitang gig",
  wGigDetail: "Ang mga resibo ng gig ay isinataon (annualized), ngunit dapat suriin laban sa mga sumusuportang ebidensya.",
  slotDescApplication: "Pagkakakilanlan, laki ng sambahayan, address, petsa ng aplikasyon.",
  slotDescPayStub: "Gross pay, dalas, oras, rate, mga petsa ng period.",
  slotDescEmployment: "Rate ng employer, iskedyul, petsa ng dokumento.",
  slotDescBenefit: "Kung naaangkop: halaga at dalas ng paulit-ulit na benepisyo.",
  slotDescGig: "Kung naaangkop: buwanang gross na kita at mga bayarin sa platform.",

  dvTitle: "Mga property",
  dvCount: "{n} pampublikong tala ng property",
  dvFiltersAria: "Mga filter ng property",
  dvCity: "Lungsod",
  dvCityAll: "Lahat ng lungsod",
  dvBedrooms: "Mga silid-tulugan",
  dvBedroomsAny: "Kahit ilan",
  dvBrStudio: "Studio",
  dvBr1: "1 silid-tulugan",
  dvBr2: "2 silid-tulugan",
  dvBr3: "3 silid-tulugan",
  dvBr4: "4 silid-tulugan",
  dvNear: "Malapit sa",
  dvNearNone: "Walang lokasyon",
  dvWithin: "Sa loob ng",
  dvAnyDistance: "Kahit gaano kalayo",
  dvWithinMi: "Sa loob ng {mi} mi",
  dvClear: "I-clear ang mga filter",
  dvMapAria: "Mapa ng mga pampublikong tala ng LIHTC property",
  dvMapStyleAria: "Istilo ng mapa",
  dvMapStandard: "Mapa",
  dvMapSatellite: "Satellite",
  dvNoRecords: "Walang talang tumutugma sa mga filter na ito.",
  dvDetailAria: "Mga detalye ng napiling property",
  dvCloseDetail: "Isara ang mga detalye ng property",
  dvPhotoAlt: "Panlabas ng property",
  dvAvailabilityUnknown: "Hindi alam ang availability",
  dvLowIncomeUnits: "Mga unit para sa mababang kita",
  dvTotalUnits: "Kabuuang unit",
  dvBedroomsRow: "Mga silid-tulugan",
  dvDistance: "Distansya",
  dvYearPlaced: "Taon ng paggamit",
  dvSource: "Pinagmulan",
  dvHudSource: "Pampublikong datos ng HUD LIHTC",
  dvViewSource: "Tingnan ang pinagmulan",
  dvCopyAddress: "Kopyahin ang address",
  dvChooseLocation: "Pumili ng lokasyon",
  dvNotReported: "Hindi naiulat",
  dvSelectPrompt: "Pumili ng property sa mapa upang makita ang mga pampublikong detalye.",
  dvMi: "{d} mi",
  viewerLabel: "Viewer ng dokumento",
  zoomIn: "Palakihin", zoomOut: "Paliitin", zoomFit: "I-fit sa lapad",
  pageOfTotal: "Pahina {n} ng {total}", snapToField: "Pumunta sa halaga",
  previewError: "Hindi maipakita ang preview. Gamitin ang link sa ibaba para buksan ang orihinal.",
  uploadTitle: "I-upload ang iyong mga dokumento",
  uploadHint:
    "I-drag ang mga PDF dito, o pumili ng mga file — mga pay stub, sulat ng benepisyo o ng employer, ang buod ng iyong aplikasyon.",
  chooseFiles: "Pumili ng mga file", reading: "Binabasa ang iyong mga dokumento…",
  noDocs: "Wala pang dokumento. Mag-upload ng isa para magsimula.",
  checklistTitle: "Listahan ng dokumento", present: "Na-upload", missing: "Kulang pa",
  docApplication_summary: "Buod ng aplikasyon",
  docPay_stub: "Pay stub",
  docEmployment_letter: "Sulat ng employer",
  docBenefit_letter: "Sulat ng benepisyo",
  docGig_statement: "Gig statement",
  docUnknown: "Dokumento",
  reviewTitle: "Kumpirmahin ang iyong mga detalye",
  reviewHint:
    "Itugma ang bawat halaga sa pinagmulan nito, pagkatapos ay kumpirmahin ito o mag-type ng pagwawasto. Ang mga kumpirmadong halaga lang ang gagamitin pagkatapos.",
  documentOf: "Dokumento {n} ng {total}",
  fieldOf: "Field {n} ng {total}",
  confirm: "Kumpirmahin", correct: "I-edit", saveCorrection: "I-save",
  cancel: "Kanselahin", confidence: "Kumpiyansa",
  stRenterEntered: "Ikaw ang naglagay",
  parameterNotPresent: "Walang parameter",
  insertManually: "Ilagay nang manu-mano",
  valueRequired: "Maglagay ng halaga bago i-save.",
  errNegative: "Error: hindi maaaring negatibo ang halaga.",
  dismiss: "Isara",
  stExtracted: "Kailangan ng iyong pagsusuri", stConfirmed: "Kumpirmado", stCorrected: "Naiwasto",
  source: "Pinagmulan",
  page: "Pahina {n}",
  openDocument: "Buksan ang orihinal na dokumento",
  whyNeeded: "Bakit kailangan ito",
  fieldExplainFallback: "{field} — na-extract mula sa {doc}.",
  allConfirmed: "Kumpirmado na ang lahat ng halaga.",
  goNextDocument: "Magpatuloy sa susunod na dokumento",
  goUnderstand: "Magpatuloy sa susunod na yugto",
  quarantineTitle: "Naka-quarantine na teksto — hindi pinansin",
  quarantineHint:
    "May mga tagubiling nakatuon sa assistant ang dokumentong ito. Hindi pinapansin ng RealDoor ang mga nakapaloob na tagubilin; ipinapakita lang ang teksto para sa transparency at hindi kailanman ginagamit bilang datos.",
  understandTitle: "Unawain ang iyong kita at ang mga patakaran",
  incomeCalcTitle: "Na-annualize na kita",
  householdSize: "Laki ng sambahayan",
  annualizedIncome: "Taunang kabuuang kita",
  incomeComposition: "Komposisyon ng taunang kita",
  incomeCompositionTitle: "Taunang kita",
  incomeCompositionSubtitle: "komposisyon",
  incomeChartEmpty: "Kumpirmahin ang halaga ng kita para mabuo ang chart.",
  incomeShare: "{pct}% ng kumpirmadong kabuuan",
  netPayChart: "Take-home pay",
  deductionsChart: "Buwis at mga kaltas",
  srcCorroborates: "nagpapatunay sa parehong source — hindi idinaragdag",
  sampleQ1: "Ano ang 60% na limitasyon sa kita para sa sambahayang apat?",
  sampleQ2: "Kailan magkakabisa ang mga limitasyon sa kita ng FY2026?",
  sampleQ3: "Paano ina-annualize ang paulit-ulit na kita?",
  sampleQ4: "Kailan nagiging handa nang suriin ang isang file?",
  mathPerPeriod: "Bawat period",
  mathPeriodsYr: "Period kada taon",
  mathCalc: "Kalkulasyon",
  mathPerYear: "Kada taon",
  mathTotal: "Kabuuan",
  srcPay: "Sahod",
  srcBenefit: "Benepisyo",
  srcGig: "Kita sa gig",
  aiThinking: "Sinusuri ang mga pinagmulan…",
  aiPrivacy:
    "Privacy ng AI: mga kumpirmadong numerong halaga, status, at sanggunian ng pinagmulan lang ang ipinapadala — hindi kailanman ang iyong mga file, teksto ng dokumento, pangalan, address, o filename. Iwasang mag-type ng personal na detalye sa tanong.",
  aiFallback: "Hindi available ang live na AI guide, kaya ginamit ng RealDoor ang lokal nitong frozen-rule fallback.",
  freqWeekly: "lingguhan", freqBiweekly: "tuwing dalawang linggo", freqSemimonthly: "dalawang beses sa isang buwan",
  freqMonthly: "buwanan", freqAnnual: "taunan",
  threshold60: "FY2026 60% na limitasyon sa kita", comparison: "Paghahambing",
  cmpBelow: "Katumbas o mas mababa sa limitasyon", cmpAbove: "Higit sa limitasyon",
  cmpNone: "Walang frozen na limitasyon para sa laki ng sambahayang ito",
  effective: "May bisa mula",
  notDecision: "Inihahambing nito ang iyong kita sa isang nakalathalang limitasyon — hindi ito desisyon sa eligibility.",
  confirmSizeNote: "Kumpirmahin ang laki ng sambahayan sa Profile para sa eksaktong limitasyon.",
  formulaHead: "Paano ito kinalkula",
  sourcesHead: "Mga pinagmulan ng kita",
  rulesTitle: "Magtanong tungkol sa mga patakaran",
  rulesHint: "Ang mga sagot ay mula lang sa frozen na rule corpus, bawat isa may citation.",
  askPlaceholder: "hal. Ano ang 60% na limitasyon para sa sambahayang apat?",
  ask: "Magtanong",
  tryAsking: "Subukang itanong",
  answerIntro: "Mula sa rule corpus:",
  aiSources: "Mga pinagmulan",
  aiGuideLabel: "Gabay ng RealDoor",
  aiCurrentDocument: "Kasalukuyang dokumento",
  aiOutcomeAnswered: "Nasagot",
  aiOutcomeRefused: "Tumanggi",
  aiOutcomeAbstained: "Hindi sumagot",
  aiOutcomeNeedsConfirmation: "Kailangan ng kumpirmasyon",
  aiOutcomeOutOfScope: "Wala sa saklaw",
  authOfficialHud: "Opisyal · HUD",
  authOfficialFederal: "Opisyal · Pederal",
  authChallenge: "Kumbensyon ng challenge",
  abstain:
    "Makakasagot lang ako mula sa frozen na rule corpus at wala akong nahanap na tumutugmang patakaran. Subukang magtanong tungkol sa mga limitasyon sa kita, petsa ng pagkakabisa, pag-a-annualize ng kita, o kahandaan ng file.",
  refusal: "Hindi masasabi ng RealDoor kung kwalipikado ka, o kung maa-aprubahan o tatanggihan ka — mga desisyon iyon ng tao. Inihahanda at sinusuri lang nito ang iyong mga papeles at inihahambing ang kita sa isang nakalathalang limitasyon.",
  prepareTitle: "Maghanda at tapusin", readinessTitle: "Kahandaan ng file",
  verdictNote: "Inilalarawan nito ang pagkakumpleto at pagkakatugma ng file — hindi ang eligibility.",
  reasonsTitle: "Ano ang dapat ayusin",
  noReasons: "Maayos ang lahat — kumpleto at magkakatugma ang file.",
  prepareIntro:
    "Suriin ang resibo sa ibaba — iwasto ang mga minarkahan ng pula, pagkatapos ay i-save ito bilang PDF o i-download ang data packet.",
  rcTitle_PAY_STUB_TOTAL_CONFLICT: "Magkasalungat ang mga total ng pay stub",
  rcTitle_GIG_INCOME_UNCORROBORATED: "Walang patunay ang kita sa gig",
  rcTitle_EMPLOYMENT_LETTER_EXPIRED: "Paso na ang sulat mula sa employer",
  rcTitle_UNCONFIRMED_FIELDS: "May mga field na hindi pa kumpirmado",
  rcTitle_LOW_CONFIDENCE_FIELDS: "May mga field na mababa ang kumpiyansa",
  rcTitle_MISSING_REQUIRED_DOCUMENT: "May kulang na inirerekomendang dokumento",
  rc_PAY_STUB_TOTAL_CONFLICT: "Hindi tugma ang nakasaad na gross ng isang pay stub sa rate kada oras × oras nito.",
  rc_GIG_INCOME_UNCORROBORATED: "Kasama ang kita sa gig ngunit kailangan pa ng patunay.",
  rc_EMPLOYMENT_LETTER_EXPIRED: "May sulat ng employer na mas luma kaysa sa 60-araw na palugit.",
  rc_UNCONFIRMED_FIELDS: "May mga field na kailangan pa ng iyong kumpirmasyon.",
  rc_LOW_CONFIDENCE_FIELDS: "May mga field na na-extract nang mababa ang kumpiyansa.",
  rc_BENEFIT_LETTER_EXPIRED: "May sulat ng benepisyo na lampas na sa 60-araw na window.",
  rc_PAY_STUB_EXPIRED: "May pay stub na lampas na sa 60-araw na window.",
  rc_GIG_STATEMENT_EXPIRED: "May gig statement na lampas na sa 60-araw na window.",
  rc_EMPLOYMENT_RATE_CONFLICT: "Iba ang rate kada oras na nakasaad sa sulat ng employer kaysa sa pay stub.",
  rc_MISSING_HOUSEHOLD_SIZE: "Walang dokumentadong laki ng sambahayan — hindi magagamit ang nakapirming talaan ng limitasyon.",
  rc_MISSING_INCOME_EVIDENCE: "Walang nahanap na dokumentadong ebidensya ng paulit-ulit na kita.",
  rc_NO_FROZEN_THRESHOLD: "Ang laki ng sambahayan ay wala sa nakapirming talaan na 1–8; walang nakapirming limitasyon.",
  rc_UNVERIFIED_INCOME_CLAIM: "May self-declared na kita na walang suportang ebidensya at hindi ibinilang.",
  rcTitle_BENEFIT_LETTER_EXPIRED: "Paso na ang sulat ng benepisyo",
  rcTitle_PAY_STUB_EXPIRED: "Paso na ang pay stub",
  rcTitle_GIG_STATEMENT_EXPIRED: "Paso na ang gig statement",
  rcTitle_EMPLOYMENT_RATE_CONFLICT: "Salungatan sa rate kada oras",
  rcTitle_MISSING_HOUSEHOLD_SIZE: "Walang laki ng sambahayan",
  rcTitle_MISSING_INCOME_EVIDENCE: "Walang ebidensya ng kita",
  rcTitle_NO_FROZEN_THRESHOLD: "Walang nakapirming limitasyon",
  rcTitle_UNVERIFIED_INCOME_CLAIM: "Hindi beripikado ang self-declared na kita",
  rc_MISSING_REQUIRED_DOCUMENT: "May inirerekomendang dokumento na hindi pa nai-upload.",
  editBtn: "I-edit", downloadBtn: "I-download ang packet",
  deleteBtn: "Burahin ang session", lockBtn: "Kumpirmahin — i-lock bilang handa nang suriin",
  unlockBtn: "I-unlock para mag-edit",
  lockedNote: "Naka-lock bilang handa nang suriin. Maaari mong i-unlock para mag-edit.",
  deleteConfirm: "Burahin ang lahat sa session na ito? Aalisin ang mga dokumento, mga na-extract na halaga, at ang resibong ito.",
  deletedProof: "Nabura na ang session. {docs} dokumento at {fields} halaga ang inalis noong {at}.",
  fieldsConfirmed: "{n} sa {total} field ang kumpirmado",
  receiptTitle: "Ang iyong resibo ng kahandaan",
  receiptPrint: "I-save bilang PDF",
  rawShow: "Tingnan ang raw na datos", rawHide: "Itago ang raw na datos",
  sampleWord: "HALIMBAWA",
  sampleBanner:
    "Ito ay isang HALIMBAWANG dokumento na ginawa mula sa datos ng iyong session. HINDI ito opisyal na form.",
  receiptKicker: "Mga papeles sa abot-kayang pabahay · Boston · HALIMBAWA",
  receiptDocTitle: "Resibo ng kahandaan ng aplikasyon",
  receiptGenerated: "Ginawa noong {date}",
  receiptFileLabel: "File",
  receiptSecDocs: "Mga dokumentong naibigay",
  receiptSecIncome: "Pagkalkula ng kita",
  receiptSecReadiness: "Kahandaan ng file",
  receiptEditNote: "Ang mga pagwawasto rito ay agad na nag-a-update sa buong file mo.",
  invalidAmount: "Maglagay ng numerong hindi negatibo, tulad ng 1250.00.",
  receiptFooter:
    "Inihanda ng RealDoor ang buod na ito para tumulong sa isang taong tagasuri. Hindi nito masasabi kung kwalipikado ka — inilalarawan lang ng kahandaan ang mga papeles. Download lang: hindi kailanman ipinapadala ang resibong ito.",
};

const vi: Copy = {
  appTitle: "Hồ sơ của bạn",
  appSubtitle: "RealDoor chuẩn bị và kiểm tra giấy tờ của bạn cho nhà ở giá phải chăng tại Boston. Không bao giờ quyết định điều kiện.",
  getStarted: "Bắt đầu",
  step1: "Hồ sơ", step2: "Tìm hiểu", step3: "Chuẩn bị",
  step1Info: "Tải lên & xác nhận", step2Info: "Thu nhập & quy định", step3Info: "Kiểm tra & xuất",
  stepLockedNote: "Hoàn thành bước trước đã",
  back: "Quay lại", next: "Tiếp theo", continue: "Tiếp tục",
  statusLabel: "Trạng thái", incomeLabel: "Tổng thu nhập", errorsLabel: "Lỗi",
  statusEmpty: "Chưa bắt đầu",
  statusProfile: "Hồ sơ · đang thực hiện",
  statusUnderstand: "Tìm hiểu · đang thực hiện",
  statusPrepare: "Chuẩn bị · đang thực hiện",
  statusReady: "Sẵn sàng xem xét", statusNeeds: "Cần xem xét",
  statusAwaiting: "{n} giá trị cần bạn xác nhận",
  fieldsNeedReview: "Một số trường cần xem xét",
  statusIssues: "Cần xem xét · {n} mục cần xử lý",
  statusMissingDocs: "Sẵn sàng xem xét · vẫn còn thiếu giấy tờ",
  statusLocked: "Đã khóa · sẵn sàng xem xét",
  errorsMenuTitle: "Những mục cần chú ý",
  errLowConfidence: "Độ tin cậy thấp — hãy kiểm tra giá trị này",

  wEyebrow: "Cảnh báo",
  wTitle: "Kiểm tra tính nhất quán",
  wOpen: "Mở",
  wUpload: "Tải lên",
  wNoFields: "Chưa trích xuất được trường nào từ tài liệu này.",
  wAriaPanel: "Cảnh báo tính nhất quán khi tải lên",
  wAriaReviewer: "Trình rà soát",
  wAriaProgress: "Tiến độ rà soát",
  wAriaStartParsing: "Bắt đầu phân tích",
  wParseFailed: "Phân tích chưa hoàn tất. Không thể kết nối tới dịch vụ tài liệu — các tệp của bạn vẫn ở trên thiết bị này. Hãy kiểm tra kết nối và nhấn Bắt đầu phân tích lần nữa.",
  wMissingRequiredTitle: "Thiếu {doc}",
  wMissingRequiredDetail: "Hãy tải lên tài liệu bắt buộc này trước khi rà soát lần cuối.",
  wTypeMismatchTitle: "Loại tài liệu không khớp",
  wTypeMismatchDetail: "{slot} được phân tích là {parsed}. Hãy kiểm tra xem tệp đã nằm đúng ô chưa.",
  wLowDocTitle: "Độ tin cậy của tài liệu thấp",
  wLowDocDetail: "Phân loại của {slot} là {pct}%. Hãy kiểm tra loại tài liệu trước khi tiếp tục.",
  wMissingFieldsTitle: "Thiếu trường được trích xuất",
  wMissingFieldsDetail: "{slot}: {list}. Hãy kiểm tra hoặc nhập thủ công nếu cần.",
  wDupFileTitle: "Có thể trùng tệp",
  wDupFileDetail: "{n} lượt tải lên dùng cùng tên tệp: {name}.",
  wDupTypeTitle: "Có thể trùng loại tài liệu",
  wDupTypeDetail: "Đã tải lên {n} tài liệu loại {doc}. Hãy kiểm tra xem tất cả có chủ ý không.",
  wNameMismatchTitle: "Tên người nộp không khớp",
  wNameMismatchDetail: "Phát hiện các tên khác nhau: {names}. Hãy kiểm tra xem mọi tài liệu có thuộc cùng một hồ sơ không.",
  wExtractErrorTitle: "Không thể trích xuất tài liệu này",
  wExtractErrorOcr: "OCR không khả dụng cục bộ, nên tài liệu scan/raster này cần Tesseract hoặc rà soát thủ công.",
  wLowFieldsTitle: "Các trường có độ tin cậy thấp",
  wLowFieldsDetail: "{doc}: {list}.",
  wQuarantineTitle: "Phát hiện chỉ dẫn không đáng tin",
  wQuarantineDetail: "Trình phân tích đã cách ly văn bản chỉ dẫn đối kháng hoặc không liên quan trong tài liệu này.",
  wPayTotalTitle: "Tổng trên phiếu lương không khớp",
  wPayTotalDetail: "Lương gộp không khớp với số giờ × đơn giá ({hours} × {rate} ≈ {total}).",
  wNetOverTitle: "Lương thực nhận cao hơn lương gộp",
  wNetOverDetail: "Lương thực nhận không nên cao hơn lương gộp. Hãy kiểm tra kết quả trích xuất.",
  wPeriodOrderTitle: "Ngày của kỳ lương có vẻ bị đảo ngược",
  wPeriodOrderDetail: "Ngày bắt đầu kỳ lương nằm sau ngày kết thúc.",
  wEmploymentStaleTitle: "Thư xác nhận việc làm có thể đã cũ",
  wEmploymentStaleDetail: "Ngày của tài liệu nằm ngoài khung hiệu lực 60 ngày.",
  wGigTitle: "Thu nhập gig cần được xác nhận thêm",
  wGigDetail: "Doanh thu gig được quy đổi theo năm, nhưng nên được đối chiếu với bằng chứng hỗ trợ.",
  slotDescApplication: "Danh tính, số người trong hộ, địa chỉ, ngày nộp đơn.",
  slotDescPayStub: "Lương gộp, tần suất, số giờ, đơn giá, ngày của kỳ lương.",
  slotDescEmployment: "Đơn giá của chủ lao động, lịch làm việc, ngày của tài liệu.",
  slotDescBenefit: "Nếu có: số tiền và tần suất trợ cấp định kỳ.",
  slotDescGig: "Nếu có: tổng doanh thu hằng tháng và phí nền tảng.",

  dvTitle: "Bất động sản",
  dvCount: "{n} bản ghi công khai về nhà ở",
  dvFiltersAria: "Bộ lọc nhà ở",
  dvCity: "Thành phố",
  dvCityAll: "Tất cả thành phố",
  dvBedrooms: "Phòng ngủ",
  dvBedroomsAny: "Bao nhiêu cũng được",
  dvBrStudio: "Studio",
  dvBr1: "1 phòng ngủ",
  dvBr2: "2 phòng ngủ",
  dvBr3: "3 phòng ngủ",
  dvBr4: "4 phòng ngủ",
  dvNear: "Gần",
  dvNearNone: "Không chọn địa điểm",
  dvWithin: "Trong phạm vi",
  dvAnyDistance: "Khoảng cách bất kỳ",
  dvWithinMi: "Trong {mi} dặm",
  dvClear: "Xóa bộ lọc",
  dvMapAria: "Bản đồ các bản ghi công khai về nhà ở LIHTC",
  dvMapStyleAria: "Kiểu bản đồ",
  dvMapStandard: "Bản đồ",
  dvMapSatellite: "Vệ tinh",
  dvNoRecords: "Không có bản ghi nào khớp với các bộ lọc này.",
  dvDetailAria: "Chi tiết nhà ở đã chọn",
  dvCloseDetail: "Đóng chi tiết nhà ở",
  dvPhotoAlt: "Bên ngoài tòa nhà",
  dvAvailabilityUnknown: "Chưa rõ tình trạng còn trống",
  dvLowIncomeUnits: "Căn hộ cho thu nhập thấp",
  dvTotalUnits: "Tổng số căn hộ",
  dvBedroomsRow: "Phòng ngủ",
  dvDistance: "Khoảng cách",
  dvYearPlaced: "Năm đưa vào sử dụng",
  dvSource: "Nguồn",
  dvHudSource: "Dữ liệu công khai HUD LIHTC",
  dvViewSource: "Xem nguồn",
  dvCopyAddress: "Sao chép địa chỉ",
  dvChooseLocation: "Hãy chọn một địa điểm",
  dvNotReported: "Không được báo cáo",
  dvSelectPrompt: "Chọn một nhà ở trên bản đồ để xem thông tin công khai.",
  dvMi: "{d} dặm",
  viewerLabel: "Trình xem tài liệu",
  zoomIn: "Phóng to", zoomOut: "Thu nhỏ", zoomFit: "Vừa chiều rộng",
  pageOfTotal: "Trang {n} / {total}", snapToField: "Đi tới giá trị",
  previewError: "Không thể hiển thị bản xem trước. Hãy dùng liên kết bên dưới để mở tài liệu gốc.",
  uploadTitle: "Tải lên giấy tờ của bạn",
  uploadHint:
    "Kéo tệp PDF vào đây hoặc chọn tệp — phiếu lương, thư trợ cấp hoặc thư xác nhận việc làm, bản tóm tắt hồ sơ của bạn.",
  chooseFiles: "Chọn tệp", reading: "Đang đọc giấy tờ của bạn…",
  noDocs: "Chưa có giấy tờ nào. Hãy tải lên một tệp để bắt đầu.",
  checklistTitle: "Danh sách giấy tờ", present: "Đã tải lên", missing: "Vẫn còn thiếu",
  docApplication_summary: "Tóm tắt hồ sơ",
  docPay_stub: "Phiếu lương",
  docEmployment_letter: "Thư xác nhận việc làm",
  docBenefit_letter: "Thư trợ cấp",
  docGig_statement: "Sao kê thu nhập gig",
  docUnknown: "Giấy tờ",
  reviewTitle: "Xác nhận thông tin của bạn",
  reviewHint:
    "Đối chiếu từng giá trị với nguồn của nó, sau đó xác nhận hoặc nhập chỉnh sửa. Chỉ các giá trị đã xác nhận mới được dùng về sau.",
  documentOf: "Tài liệu {n} / {total}",
  fieldOf: "Mục {n} / {total}",
  confirm: "Xác nhận", correct: "Chỉnh sửa", saveCorrection: "Lưu",
  cancel: "Hủy", confidence: "Độ tin cậy",
  stRenterEntered: "Do bạn nhập",
  parameterNotPresent: "Không có tham số",
  insertManually: "Nhập thủ công",
  valueRequired: "Nhập một giá trị trước khi lưu.",
  errNegative: "Lỗi: số tiền không được là số âm.",
  dismiss: "Đóng",
  stExtracted: "Cần bạn kiểm tra", stConfirmed: "Đã xác nhận", stCorrected: "Đã sửa",
  source: "Nguồn",
  page: "Trang {n}",
  openDocument: "Mở tài liệu gốc",
  whyNeeded: "Vì sao cần thông tin này",
  fieldExplainFallback: "{field} — trích xuất từ {doc}.",
  allConfirmed: "Đã xác nhận tất cả giá trị.",
  goNextDocument: "Tiếp tục đến tài liệu tiếp theo",
  goUnderstand: "Chuyển sang giai đoạn tiếp theo",
  quarantineTitle: "Văn bản bị cách ly — đã bỏ qua",
  quarantineHint:
    "Tài liệu này chứa các chỉ dẫn nhắm vào trợ lý. RealDoor bỏ qua các chỉ dẫn nhúng; văn bản chỉ được hiển thị để minh bạch và không bao giờ được dùng làm dữ liệu.",
  understandTitle: "Tìm hiểu thu nhập và quy định",
  incomeCalcTitle: "Thu nhập quy đổi theo năm",
  householdSize: "Số người trong hộ",
  annualizedIncome: "Tổng thu nhập theo năm",
  incomeComposition: "Cơ cấu thu nhập hằng năm",
  incomeCompositionTitle: "Thu nhập hằng năm",
  incomeCompositionSubtitle: "cơ cấu",
  incomeChartEmpty: "Xác nhận một giá trị thu nhập để tạo biểu đồ.",
  incomeShare: "{pct}% tổng đã xác nhận",
  netPayChart: "Thu nhập thực nhận",
  deductionsChart: "Thuế và khấu trừ",
  srcCorroborates: "xác nhận cùng một nguồn — không cộng thêm",
  sampleQ1: "Giới hạn thu nhập 60% cho hộ bốn người là bao nhiêu?",
  sampleQ2: "Giới hạn thu nhập FY2026 có hiệu lực khi nào?",
  sampleQ3: "Thu nhập định kỳ được quy đổi theo năm như thế nào?",
  sampleQ4: "Khi nào hồ sơ sẵn sàng để xem xét?",
  mathPerPeriod: "Mỗi kỳ",
  mathPeriodsYr: "Số kỳ / năm",
  mathCalc: "Phép tính",
  mathPerYear: "Mỗi năm",
  mathTotal: "Tổng",
  srcPay: "Tiền lương",
  srcBenefit: "Trợ cấp",
  srcGig: "Thu nhập gig",
  aiThinking: "Đang kiểm tra nguồn…",
  aiPrivacy:
    "Quyền riêng tư AI: chỉ gửi các giá trị số đã xác nhận, trạng thái và tham chiếu nguồn — không bao giờ gửi tệp, nội dung tài liệu, tên, địa chỉ hay tên tệp của bạn. Tránh nhập thông tin cá nhân vào câu hỏi.",
  aiFallback: "Trợ lý AI trực tuyến không khả dụng, RealDoor đã dùng phương án dự phòng quy tắc cố định cục bộ.",
  freqWeekly: "hằng tuần", freqBiweekly: "hai tuần một lần", freqSemimonthly: "nửa tháng một lần",
  freqMonthly: "hằng tháng", freqAnnual: "hằng năm",
  threshold60: "Giới hạn thu nhập 60% (FY2026)", comparison: "So sánh",
  cmpBelow: "Bằng hoặc thấp hơn giới hạn", cmpAbove: "Cao hơn giới hạn",
  cmpNone: "Không có ngưỡng cố định cho số người này trong hộ",
  effective: "Hiệu lực từ",
  notDecision: "Điều này so sánh thu nhập của bạn với giới hạn đã công bố — không phải quyết định điều kiện.",
  confirmSizeNote: "Xác nhận số người trong hộ ở bước Hồ sơ để có ngưỡng chính xác.",
  formulaHead: "Cách tính",
  sourcesHead: "Nguồn thu nhập",
  rulesTitle: "Hỏi về các quy định",
  rulesHint: "Câu trả lời chỉ đến từ bộ quy tắc cố định, mỗi câu kèm trích dẫn.",
  askPlaceholder: "vd. Giới hạn 60% cho hộ bốn người là bao nhiêu?",
  ask: "Hỏi",
  tryAsking: "Thử hỏi",
  answerIntro: "Từ bộ quy tắc:",
  aiSources: "Nguồn",
  aiGuideLabel: "Hướng dẫn RealDoor",
  aiCurrentDocument: "Tài liệu hiện tại",
  aiOutcomeAnswered: "Đã trả lời",
  aiOutcomeRefused: "Đã từ chối trả lời",
  aiOutcomeAbstained: "Không trả lời",
  aiOutcomeNeedsConfirmation: "Cần xác nhận",
  aiOutcomeOutOfScope: "Ngoài phạm vi",
  authOfficialHud: "Chính thức · HUD",
  authOfficialFederal: "Chính thức · Liên bang",
  authChallenge: "Quy ước cuộc thi",
  abstain:
    "Tôi chỉ có thể trả lời từ bộ quy tắc cố định và không tìm thấy quy tắc phù hợp. Hãy thử hỏi về giới hạn thu nhập, ngày hiệu lực, cách quy đổi thu nhập theo năm, hoặc mức độ sẵn sàng của hồ sơ.",
  refusal: "RealDoor không thể cho biết bạn có đủ điều kiện hay không, hay bạn sẽ được chấp thuận hoặc bị từ chối — đó là các quyết định của con người. Nó chỉ chuẩn bị, kiểm tra giấy tờ và so sánh thu nhập với một giới hạn đã công bố.",
  prepareTitle: "Chuẩn bị và hoàn tất", readinessTitle: "Mức độ sẵn sàng của hồ sơ",
  verdictNote: "Điều này mô tả mức độ đầy đủ và nhất quán của hồ sơ — không bao giờ là điều kiện.",
  reasonsTitle: "Cần xử lý",
  noReasons: "Mọi thứ đều ổn — hồ sơ đầy đủ và nhất quán.",
  prepareIntro:
    "Kiểm tra biên nhận bên dưới — sửa những mục được đánh dấu đỏ, sau đó lưu thành PDF hoặc tải gói dữ liệu.",
  rcTitle_PAY_STUB_TOTAL_CONFLICT: "Tổng số trên phiếu lương không khớp",
  rcTitle_GIG_INCOME_UNCORROBORATED: "Thu nhập tự do chưa có bằng chứng",
  rcTitle_EMPLOYMENT_LETTER_EXPIRED: "Thư xác nhận việc làm đã hết hạn",
  rcTitle_UNCONFIRMED_FIELDS: "Các trường chưa được xác nhận",
  rcTitle_LOW_CONFIDENCE_FIELDS: "Các trường có độ tin cậy thấp",
  rcTitle_MISSING_REQUIRED_DOCUMENT: "Thiếu tài liệu được khuyến nghị",
  rc_PAY_STUB_TOTAL_CONFLICT: "Tổng lương ghi trên một phiếu lương không khớp với đơn giá theo giờ × số giờ.",
  rc_GIG_INCOME_UNCORROBORATED: "Thu nhập gig đã được tính nhưng cần thêm chứng thực.",
  rc_EMPLOYMENT_LETTER_EXPIRED: "Một thư xác nhận việc làm cũ hơn khung hiệu lực 60 ngày.",
  rc_UNCONFIRMED_FIELDS: "Một số mục vẫn cần bạn xác nhận.",
  rc_LOW_CONFIDENCE_FIELDS: "Một số mục được trích xuất với độ tin cậy thấp.",
  rc_BENEFIT_LETTER_EXPIRED: "Một thư trợ cấp đã quá cửa sổ hiệu lực 60 ngày.",
  rc_PAY_STUB_EXPIRED: "Một phiếu lương đã quá cửa sổ hiệu lực 60 ngày.",
  rc_GIG_STATEMENT_EXPIRED: "Một bảng kê thu nhập gig đã quá cửa sổ hiệu lực 60 ngày.",
  rc_EMPLOYMENT_RATE_CONFLICT: "Thư của chủ lao động ghi đơn giá giờ khác với phiếu lương.",
  rc_MISSING_HOUSEHOLD_SIZE: "Không có số người trong hộ được ghi nhận — không thể áp dụng bảng ngưỡng cố định.",
  rc_MISSING_INCOME_EVIDENCE: "Không tìm thấy bằng chứng thu nhập định kỳ được ghi nhận.",
  rc_NO_FROZEN_THRESHOLD: "Quy mô hộ nằm ngoài bảng cố định 1–8; không có ngưỡng cố định.",
  rc_UNVERIFIED_INCOME_CLAIM: "Một khoản thu nhập tự khai không có bằng chứng hỗ trợ và không được tính.",
  rcTitle_BENEFIT_LETTER_EXPIRED: "Thư trợ cấp hết hạn",
  rcTitle_PAY_STUB_EXPIRED: "Phiếu lương hết hạn",
  rcTitle_GIG_STATEMENT_EXPIRED: "Bảng kê gig hết hạn",
  rcTitle_EMPLOYMENT_RATE_CONFLICT: "Xung đột đơn giá giờ",
  rcTitle_MISSING_HOUSEHOLD_SIZE: "Thiếu số người trong hộ",
  rcTitle_MISSING_INCOME_EVIDENCE: "Thiếu bằng chứng thu nhập",
  rcTitle_NO_FROZEN_THRESHOLD: "Không có ngưỡng cố định",
  rcTitle_UNVERIFIED_INCOME_CLAIM: "Thu nhập tự khai chưa xác minh",
  rc_MISSING_REQUIRED_DOCUMENT: "Một giấy tờ được khuyến nghị vẫn chưa được tải lên.",
  editBtn: "Chỉnh sửa", downloadBtn: "Tải gói hồ sơ",
  deleteBtn: "Xóa phiên", lockBtn: "Xác nhận — khóa là sẵn sàng xem xét",
  unlockBtn: "Mở khóa để chỉnh sửa",
  lockedNote: "Đã khóa là sẵn sàng xem xét. Bạn có thể mở khóa để chỉnh sửa.",
  deleteConfirm: "Xóa mọi thứ trong phiên này? Giấy tờ, các giá trị đã trích xuất và biên nhận này sẽ bị xóa.",
  deletedProof: "Đã xóa phiên. Đã gỡ {docs} giấy tờ và {fields} giá trị lúc {at}.",
  fieldsConfirmed: "Đã xác nhận {n} / {total} mục",
  receiptTitle: "Biên nhận mức độ sẵn sàng của bạn",
  receiptPrint: "Lưu dưới dạng PDF",
  rawShow: "Xem dữ liệu thô", rawHide: "Ẩn dữ liệu thô",
  sampleWord: "BẢN MẪU",
  sampleBanner:
    "Đây là tài liệu BẢN MẪU được tạo từ dữ liệu phiên của bạn. Đây KHÔNG phải là biểu mẫu chính thức.",
  receiptKicker: "Giấy tờ nhà ở giá phải chăng · Boston · BẢN MẪU",
  receiptDocTitle: "Biên nhận mức độ sẵn sàng của hồ sơ",
  receiptGenerated: "Tạo ngày {date}",
  receiptFileLabel: "Hồ sơ",
  receiptSecDocs: "Giấy tờ đã cung cấp",
  receiptSecIncome: "Tính toán thu nhập",
  receiptSecReadiness: "Mức độ sẵn sàng của hồ sơ",
  receiptEditNote: "Các chỉnh sửa tại đây sẽ cập nhật toàn bộ hồ sơ của bạn ngay lập tức.",
  invalidAmount: "Nhập một số không âm, ví dụ 1250.00.",
  receiptFooter:
    "RealDoor chuẩn bị bản tóm tắt này để hỗ trợ người xét duyệt. Nó không thể cho bạn biết bạn có đủ điều kiện hay không — mức độ sẵn sàng chỉ mô tả giấy tờ. Chỉ để tải xuống: biên nhận này không bao giờ được truyền đi.",
};

const COPIES: Record<Language, Copy> = { en, es, zh, tl, vi };

// Localized labels for parsed-document field keys (receipt rows, field review).
// English is complete; other languages fall back en → humanized key.
const FIELD_LABELS_EN: Record<string, string> = {
  person_name: "Person name",
  household_size: "Household size",
  address: "Address",
  application_date: "Application date",
  declared_income: "Declared income",
  pay_date: "Pay date",
  pay_frequency: "Pay frequency",
  pay_period_start: "Pay period start",
  pay_period_end: "Pay period end",
  regular_hours: "Regular hours",
  hourly_rate: "Hourly rate",
  gross_pay: "Gross pay",
  net_pay: "Net pay",
  document_date: "Document date",
  weekly_hours: "Weekly hours",
  benefit_frequency: "Benefit frequency",
  benefit_amount: "Benefit amount",
  weekly_benefit: "Weekly benefit",
  biweekly_benefit: "Biweekly benefit",
  semimonthly_benefit: "Semimonthly benefit",
  monthly_benefit: "Monthly benefit",
  annual_benefit: "Annual benefit",
  statement_month: "Statement month",
  gross_receipts: "Gross receipts",
  platform_fees: "Platform fees",
};

export const FIELD_LABELS: Record<Language, Record<string, string>> = {
  en: FIELD_LABELS_EN,
  es: {
    person_name: "Nombre", household_size: "Tamaño del hogar", address: "Dirección",
    application_date: "Fecha de solicitud", declared_income: "Ingresos declarados",
    pay_date: "Fecha de pago", pay_frequency: "Frecuencia de pago",
    pay_period_start: "Inicio del período de pago", pay_period_end: "Fin del período de pago",
    regular_hours: "Horas regulares", hourly_rate: "Tarifa por hora",
    gross_pay: "Pago bruto", net_pay: "Pago neto", document_date: "Fecha del documento",
    weekly_hours: "Horas semanales", benefit_frequency: "Frecuencia del beneficio",
    benefit_amount: "Monto del beneficio", weekly_benefit: "Beneficio semanal",
    biweekly_benefit: "Beneficio quincenal", semimonthly_benefit: "Beneficio semimensual",
    monthly_benefit: "Beneficio mensual", annual_benefit: "Beneficio anual",
    statement_month: "Mes del estado", gross_receipts: "Ingresos brutos",
    platform_fees: "Comisiones de la plataforma",
  },
  zh: {
    person_name: "姓名", household_size: "家庭人数", address: "地址",
    application_date: "申请日期", declared_income: "申报收入",
    pay_date: "发薪日期", pay_frequency: "发薪频率",
    pay_period_start: "工资周期开始", pay_period_end: "工资周期结束",
    regular_hours: "正常工时", hourly_rate: "时薪",
    gross_pay: "总工资", net_pay: "实发工资", document_date: "文件日期",
    weekly_hours: "每周工时", benefit_frequency: "福利发放频率",
    benefit_amount: "福利金额", weekly_benefit: "每周福利",
    biweekly_benefit: "双周福利", semimonthly_benefit: "半月福利",
    monthly_benefit: "每月福利", annual_benefit: "年度福利",
    statement_month: "报表月份", gross_receipts: "总收入", platform_fees: "平台费用",
  },
  tl: {
    person_name: "Pangalan", household_size: "Laki ng sambahayan", address: "Address",
    application_date: "Petsa ng aplikasyon", declared_income: "Idineklarang kita",
    pay_date: "Petsa ng sahod", pay_frequency: "Dalas ng sahod",
    pay_period_start: "Simula ng panahon ng sahod", pay_period_end: "Katapusan ng panahon ng sahod",
    regular_hours: "Regular na oras", hourly_rate: "Singil kada oras",
    gross_pay: "Gross na sahod", net_pay: "Net na sahod", document_date: "Petsa ng dokumento",
    weekly_hours: "Oras kada linggo", benefit_frequency: "Dalas ng benepisyo",
    benefit_amount: "Halaga ng benepisyo", weekly_benefit: "Lingguhang benepisyo",
    biweekly_benefit: "Benepisyo kada dalawang linggo", semimonthly_benefit: "Benepisyo kada kalahating buwan",
    monthly_benefit: "Buwanang benepisyo", annual_benefit: "Taunang benepisyo",
    statement_month: "Buwan ng ulat", gross_receipts: "Gross na kita", platform_fees: "Bayarin sa platform",
  },
  vi: {
    person_name: "Họ tên", household_size: "Quy mô hộ gia đình", address: "Địa chỉ",
    application_date: "Ngày nộp đơn", declared_income: "Thu nhập kê khai",
    pay_date: "Ngày trả lương", pay_frequency: "Tần suất trả lương",
    pay_period_start: "Bắt đầu kỳ lương", pay_period_end: "Kết thúc kỳ lương",
    regular_hours: "Số giờ chuẩn", hourly_rate: "Lương theo giờ",
    gross_pay: "Lương gộp", net_pay: "Lương thực nhận", document_date: "Ngày của tài liệu",
    weekly_hours: "Số giờ mỗi tuần", benefit_frequency: "Tần suất trợ cấp",
    benefit_amount: "Số tiền trợ cấp", weekly_benefit: "Trợ cấp hằng tuần",
    biweekly_benefit: "Trợ cấp hai tuần", semimonthly_benefit: "Trợ cấp nửa tháng",
    monthly_benefit: "Trợ cấp hằng tháng", annual_benefit: "Trợ cấp hằng năm",
    statement_month: "Tháng sao kê", gross_receipts: "Tổng doanh thu", platform_fees: "Phí nền tảng",
  },
};

export function useCopy(): Copy {
  const { language } = useI18n();
  return COPIES[language];
}

export function fmt(template: string, vars: Record<string, string | number>): string {
  return template.replace(/\{(\w+)\}/g, (_, k) => String(vars[k] ?? `{${k}}`));
}
