"use client";

// Pipeline copy, localized. English is the complete source of truth; the other
// four supported languages provide the always-visible chrome and fall back to
// English for longer strings (spread-merge below). Kept separate from
// dictionaries.ts to avoid churn on that actively-developed file; can be folded
// in later. Voice: calm, plain, non-decisional — in every language.

import { useI18n } from "@/lib/i18n";
import type { Language } from "@/lib/dictionaries";

const en = {
  appTitle: "Your application",
  appSubtitle: "RealDoor prepares and checks your paperwork. It never decides eligibility.",
  getStarted: "Get started",
  step1: "Profile",
  step2: "Understand",
  step3: "Prepare",
  step1Info: "Upload & confirm",
  step2Info: "Income & rules",
  step3Info: "Check & export",
  stepLockedNote: "Finish the previous step first",
  back: "Back",
  next: "Next",
  continue: "Continue",

  statusLabel: "Status",
  incomeLabel: "Gross income",
  errorsLabel: "Errors",
  statusEmpty: "Not started",
  statusProfile: "Profile · in progress",
  statusUnderstand: "Understand · in progress",
  statusPrepare: "Prepare · in progress",
  statusReady: "Ready to review",
  statusNeeds: "Needs review",
  statusAwaiting: "{n} values need your confirmation",
  statusIssues: "Needs review · {n} to resolve",
  statusMissingDocs: "Ready to review · documents still missing",
  statusLocked: "Locked · ready to review",
  errorsMenuTitle: "What needs attention",
  errLowConfidence: "Low confidence — check this value",

  uploadTitle: "Upload your documents",
  uploadHint: "Drag PDFs here, or choose files — pay stubs, benefit or employment letters, your application summary.",
  chooseFiles: "Choose files",
  reading: "Reading your documents…",
  noDocs: "No documents yet. Upload one to begin.",
  checklistTitle: "Documents checklist",
  present: "Uploaded",
  missing: "Still missing",

  docApplication_summary: "Application summary",
  docPay_stub: "Pay stub",
  docEmployment_letter: "Employment letter",
  docBenefit_letter: "Benefit letter",
  docGig_statement: "Gig statement",
  docUnknown: "Document",

  reviewTitle: "Confirm your details",
  reviewHint: "Check each value against its source, then confirm it or type a correction. Only confirmed values are used later.",
  fieldOf: "Field {n} of {total}",
  confirm: "Confirm",
  correct: "Correct",
  saveCorrection: "Save",
  cancel: "Cancel",
  confidence: "Confidence",
  stExtracted: "Needs your check",
  stConfirmed: "Confirmed",
  stCorrected: "Corrected",
  source: "Source",
  page: "Page {n}",
  openDocument: "Open original document",
  whyNeeded: "Why this is needed",
  allConfirmed: "All values confirmed.",
  goUnderstand: "Continue to Understand",

  quarantineTitle: "Quarantined text — ignored",
  quarantineHint:
    "This document contained instructions aimed at the assistant. RealDoor ignores embedded instructions; the text is shown only for transparency and is never used as data.",

  understandTitle: "Understand your income and the rules",
  incomeCalcTitle: "Annualized income",
  householdSize: "Household size",
  annualizedIncome: "Annualized gross income",
  threshold60: "FY2026 60% income limit",
  comparison: "Comparison",
  cmpBelow: "At or below the published limit",
  cmpAbove: "Above the published limit",
  cmpNone: "No frozen threshold for this household size",
  effective: "Effective",
  notDecision: "This compares your income to a published limit — it is not an eligibility decision.",
  confirmSizeNote: "Confirm the household size in Profile for an exact threshold.",
  formulaHead: "How this was calculated",
  sourcesHead: "Income sources",

  rulesTitle: "Ask about the rules",
  rulesHint: "Answers come only from the frozen rule corpus, each with its citation.",
  askPlaceholder: "e.g. What is the 60% limit for a household of four?",
  ask: "Ask",
  tryAsking: "Try asking",
  answerIntro: "From the rule corpus:",
  abstain:
    "I can only answer from the frozen rule corpus and didn't find a matching rule. Try asking about income limits, the effective date, annualizing income, or readiness.",
  refusal:
    "RealDoor can't tell you whether you qualify, or whether you'll be approved or denied — those remain human decisions. It only prepares and checks your paperwork and compares income to a published limit.",
  aiThinking: "Checking sources…",
  aiPrivacy:
    "AI privacy: only confirmed numeric values, statuses, and source references are sent — never your files, raw document text, name, address, or filename. Avoid typing personal details in the question.",
  aiFallback: "The live AI guide was unavailable, so RealDoor used its local frozen-rule fallback.",

  prepareTitle: "Prepare and finish",
  readinessTitle: "File readiness",
  verdictNote: "This describes the file's completeness and consistency — never eligibility.",
  reasonsTitle: "What to resolve",
  noReasons: "Everything checks out — the file is complete and consistent.",
  prepareIntro:
    "Check your receipt below — correct anything marked in red, then save it as a PDF or download the data packet.",
  rc_PAY_STUB_TOTAL_CONFLICT: "A pay stub's stated gross doesn't match its hourly rate × hours.",
  rc_GIG_INCOME_UNCORROBORATED: "Gig income is included but needs corroboration.",
  rc_EMPLOYMENT_LETTER_EXPIRED: "An employment letter is older than the 60-day currency window.",
  rc_UNCONFIRMED_FIELDS: "Some fields still need your confirmation.",
  rc_LOW_CONFIDENCE_FIELDS: "Some fields were extracted with low confidence.",
  rc_MISSING_REQUIRED_DOCUMENT: "A recommended document hasn't been uploaded yet.",
  editBtn: "Edit details",
  downloadBtn: "Download packet",
  deleteBtn: "Delete session",
  deleteConfirm: "Delete everything in this session? Documents, extracted values, and this receipt will be removed.",
  deletedProof: "Session deleted. {docs} documents and {fields} values removed at {at}.",
  lockBtn: "Confirm — lock as ready to review",
  unlockBtn: "Unlock to edit",
  lockedNote: "Locked as ready to review. You can unlock to edit.",
  fieldsConfirmed: "{n} of {total} fields confirmed",

  receiptTitle: "Your readiness receipt",
  receiptPrint: "Save receipt as PDF",
  rawShow: "View raw data",
  rawHide: "Hide raw data",
  sampleWord: "SAMPLE",
  sampleBanner:
    "This is a SAMPLE document generated from your session data. It is not an official form and is never sent anywhere.",
  receiptKicker: "Affordable housing paperwork · Boston · SAMPLE",
  receiptDocTitle: "Application readiness receipt",
  receiptGenerated: "Generated {date}",
  receiptFileLabel: "File",
  receiptSecDocs: "Documents provided",
  receiptSecIncome: "Income calculation",
  receiptSecReadiness: "File readiness",
  receiptEditNote: "Corrections here update your whole file instantly.",
  invalidAmount: "Enter a non-negative number, like 1250.00.",
  receiptFooter:
    "RealDoor prepared this summary to help a human reviewer. It can't tell you whether you qualify — readiness describes the paperwork only. Download-only: this receipt is never transmitted.",
};

export type Copy = typeof en;

const es: Partial<Copy> = {
  appTitle: "Tu solicitud",
  appSubtitle: "RealDoor prepara y revisa tus documentos. Nunca decide la elegibilidad.",
  getStarted: "Empezar",
  step1: "Perfil", step2: "Entender", step3: "Preparar",
  step1Info: "Subir y confirmar", step2Info: "Ingresos y reglas", step3Info: "Revisar y exportar",
  stepLockedNote: "Completa primero el paso anterior",
  back: "Atrás", next: "Siguiente", continue: "Continuar",
  statusLabel: "Estado", incomeLabel: "Ingreso bruto", errorsLabel: "Errores",
  statusEmpty: "Sin empezar", statusReady: "Listo para revisar", statusNeeds: "Necesita revisión",
  statusAwaiting: "{n} valores necesitan tu confirmación",
  statusIssues: "Necesita revisión · {n} por resolver",
  statusMissingDocs: "Listo para revisar · aún faltan documentos",
  statusLocked: "Bloqueado · listo para revisar",
  errorsMenuTitle: "Qué necesita atención",
  errLowConfidence: "Confianza baja — revisa este valor",
  uploadTitle: "Sube tus documentos", chooseFiles: "Elegir archivos", reading: "Leyendo tus documentos…",
  checklistTitle: "Lista de documentos", present: "Subido", missing: "Aún falta",
  reviewTitle: "Confirma tus datos", confirm: "Confirmar", correct: "Corregir", saveCorrection: "Guardar",
  cancel: "Cancelar", confidence: "Confianza", source: "Fuente", whyNeeded: "Por qué se necesita",
  understandTitle: "Entiende tus ingresos y las reglas", annualizedIncome: "Ingreso bruto anualizado",
  threshold60: "Límite de ingresos del 60% (FY2026)", comparison: "Comparación",
  cmpBelow: "Igual o por debajo del límite", cmpAbove: "Por encima del límite",
  notDecision: "Esto compara tus ingresos con un límite publicado — no es una decisión de elegibilidad.",
  rulesTitle: "Pregunta sobre las reglas", ask: "Preguntar",
  refusal: "RealDoor no puede decirte si cumples los requisitos, ni si serás aprobado o rechazado — esas son decisiones humanas. Solo prepara y revisa tus documentos y compara los ingresos con un límite publicado.",
  prepareTitle: "Prepara y finaliza", readinessTitle: "Preparación del expediente",
  verdictNote: "Describe qué tan completo y coherente está el expediente — nunca la elegibilidad.",
  prepareIntro:
    "Revisa tu recibo abajo — corrige lo marcado en rojo y luego guárdalo como PDF o descarga el paquete de datos.",
  editBtn: "Editar datos", downloadBtn: "Descargar paquete",
  deleteBtn: "Borrar sesión", lockBtn: "Confirmar — marcar como listo para revisar",
  deleteConfirm: "¿Borrar todo en esta sesión? Se eliminarán los documentos, los valores extraídos y este recibo.",
  receiptTitle: "Tu recibo de preparación",
  receiptPrint: "Guardar recibo como PDF",
  rawShow: "Ver datos sin procesar", rawHide: "Ocultar datos sin procesar",
  sampleWord: "MUESTRA",
  sampleBanner:
    "Este es un documento de MUESTRA generado con los datos de tu sesión. No es un formulario oficial y nunca se envía a ninguna parte.",
  receiptKicker: "Documentos de vivienda asequible · Boston · MUESTRA",
  receiptDocTitle: "Recibo de preparación de la solicitud",
  receiptGenerated: "Generado el {date}",
  receiptFileLabel: "Expediente",
  receiptSecDocs: "Documentos entregados",
  receiptSecIncome: "Cálculo de ingresos",
  receiptSecReadiness: "Preparación del expediente",
  receiptEditNote: "Las correcciones aquí actualizan todo tu expediente al instante.",
  invalidAmount: "Introduce un número no negativo, como 1250.00.",
  receiptFooter:
    "RealDoor preparó este resumen para ayudar a un revisor humano. No puede decirte si cumples los requisitos — la preparación describe solo los documentos. Solo descarga: este recibo nunca se transmite.",
};

const zh: Partial<Copy> = {
  appTitle: "您的申请",
  appSubtitle: "RealDoor 帮您准备并核对材料，绝不判定资格。",
  getStarted: "开始",
  step1: "个人资料", step2: "了解", step3: "准备",
  step1Info: "上传并确认", step2Info: "收入与规则", step3Info: "检查并导出",
  stepLockedNote: "请先完成上一步",
  back: "返回", next: "下一步", continue: "继续",
  statusLabel: "状态", incomeLabel: "总收入", errorsLabel: "错误",
  statusEmpty: "未开始", statusReady: "可供审核", statusNeeds: "需要复核",
  statusAwaiting: "{n} 项信息待您确认",
  statusIssues: "需要复核 · {n} 项待解决",
  statusMissingDocs: "可供审核 · 仍缺少文件",
  statusLocked: "已锁定 · 可供审核",
  errorsMenuTitle: "需要处理的事项",
  errLowConfidence: "置信度低——请核对此值",
  uploadTitle: "上传您的文件", chooseFiles: "选择文件", reading: "正在读取您的文件…",
  checklistTitle: "文件清单", present: "已上传", missing: "仍缺少",
  reviewTitle: "确认您的信息", confirm: "确认", correct: "更正", saveCorrection: "保存",
  cancel: "取消", confidence: "置信度", source: "来源", whyNeeded: "为何需要",
  understandTitle: "了解您的收入与规则", annualizedIncome: "年化总收入",
  threshold60: "2026 财年 60% 收入上限", comparison: "比较",
  cmpBelow: "等于或低于上限", cmpAbove: "高于上限",
  notDecision: "这是将您的收入与公布上限比较——并非资格判定。",
  rulesTitle: "咨询相关规则", ask: "提问",
  refusal: "RealDoor 无法告诉您是否符合资格，也无法判定批准或拒绝——这些属于人工决定。它只帮您准备和核对材料，并将收入与公布的上限进行比较。",
  prepareTitle: "准备并完成", readinessTitle: "材料就绪情况",
  verdictNote: "这说明材料的完整性与一致性——绝不涉及资格。",
  prepareIntro: "请检查下方的回执——更正标为红色的内容，然后将其保存为 PDF 或下载数据包。",
  editBtn: "编辑信息", downloadBtn: "下载材料包",
  deleteBtn: "删除会话", lockBtn: "确认——标记为可供审核",
  deleteConfirm: "删除本会话中的所有内容？文件、提取的数值和此回执都将被移除。",
  receiptTitle: "您的就绪回执",
  receiptPrint: "将回执保存为 PDF",
  rawShow: "查看原始数据", rawHide: "隐藏原始数据",
  sampleWord: "样本",
  sampleBanner: "这是根据您的会话数据生成的样本文件。它不是官方表格，也绝不会被发送到任何地方。",
  receiptKicker: "可负担住房材料 · 波士顿 · 样本",
  receiptDocTitle: "申请就绪回执",
  receiptGenerated: "生成于 {date}",
  receiptFileLabel: "档案",
  receiptSecDocs: "已提供的文件",
  receiptSecIncome: "收入计算",
  receiptSecReadiness: "材料就绪情况",
  receiptEditNote: "在此处的更正会立即更新您的整个档案。",
  invalidAmount: "请输入非负数字，例如 1250.00。",
  receiptFooter:
    "RealDoor 准备本摘要以协助人工审核。它无法告诉您是否符合资格——就绪仅描述材料本身。仅供下载：此回执绝不会被传送。",
};

const tl: Partial<Copy> = {
  appTitle: "Ang iyong aplikasyon",
  appSubtitle: "Inihahanda at sinusuri ng RealDoor ang iyong mga papeles. Hindi ito nagpapasya ng eligibility.",
  getStarted: "Magsimula",
  step1: "Profile", step2: "Unawain", step3: "Maghanda",
  step1Info: "I-upload at kumpirmahin", step2Info: "Kita at patakaran", step3Info: "Suriin at i-export",
  stepLockedNote: "Tapusin muna ang naunang hakbang",
  back: "Bumalik", next: "Susunod", continue: "Magpatuloy",
  statusLabel: "Katayuan", incomeLabel: "Kabuuang kita", errorsLabel: "Mga error",
  statusEmpty: "Hindi pa nagsisimula", statusReady: "Handa nang suriin", statusNeeds: "Kailangang suriin",
  statusAwaiting: "{n} na halaga ang kailangang kumpirmahin",
  statusIssues: "Kailangang suriin · {n} ang dapat ayusin",
  statusMissingDocs: "Handa nang suriin · may kulang pang dokumento",
  statusLocked: "Naka-lock · handa nang suriin",
  errorsMenuTitle: "Ano ang kailangang asikasuhin",
  errLowConfidence: "Mababa ang kumpiyansa — suriin ang halagang ito",
  uploadTitle: "I-upload ang iyong mga dokumento", chooseFiles: "Pumili ng mga file", reading: "Binabasa ang iyong mga dokumento…",
  checklistTitle: "Listahan ng dokumento", present: "Na-upload", missing: "Kulang pa",
  reviewTitle: "Kumpirmahin ang iyong mga detalye", confirm: "Kumpirmahin", correct: "Iwasto", saveCorrection: "I-save",
  cancel: "Kanselahin", confidence: "Kumpiyansa", source: "Pinagmulan", whyNeeded: "Bakit kailangan ito",
  understandTitle: "Unawain ang iyong kita at ang mga patakaran", annualizedIncome: "Taunang kabuuang kita",
  threshold60: "FY2026 60% na limitasyon sa kita", comparison: "Paghahambing",
  cmpBelow: "Katumbas o mas mababa sa limitasyon", cmpAbove: "Higit sa limitasyon",
  notDecision: "Inihahambing nito ang iyong kita sa isang nakalathalang limitasyon — hindi ito desisyon sa eligibility.",
  rulesTitle: "Magtanong tungkol sa mga patakaran", ask: "Magtanong",
  refusal: "Hindi masasabi ng RealDoor kung kwalipikado ka, o kung maa-aprubahan o tatanggihan ka — mga desisyon iyon ng tao. Inihahanda at sinusuri lang nito ang iyong mga papeles at inihahambing ang kita sa isang nakalathalang limitasyon.",
  prepareTitle: "Maghanda at tapusin", readinessTitle: "Kahandaan ng file",
  verdictNote: "Inilalarawan nito ang pagkakumpleto at pagkakatugma ng file — hindi ang eligibility.",
  prepareIntro:
    "Suriin ang resibo sa ibaba — iwasto ang mga minarkahan ng pula, pagkatapos ay i-save ito bilang PDF o i-download ang data packet.",
  editBtn: "I-edit ang mga detalye", downloadBtn: "I-download ang packet",
  deleteBtn: "Burahin ang session", lockBtn: "Kumpirmahin — i-lock bilang handa nang suriin",
  deleteConfirm: "Burahin ang lahat sa session na ito? Aalisin ang mga dokumento, mga na-extract na halaga, at ang resibong ito.",
  receiptTitle: "Ang iyong resibo ng kahandaan",
  receiptPrint: "I-save ang resibo bilang PDF",
  rawShow: "Tingnan ang raw na datos", rawHide: "Itago ang raw na datos",
  sampleWord: "HALIMBAWA",
  sampleBanner:
    "Ito ay isang HALIMBAWANG dokumento na ginawa mula sa datos ng iyong session. Hindi ito opisyal na form at hindi kailanman ipinapadala kahit saan.",
  receiptKicker: "Mga papeles sa abot-kayang pabahay · Boston · HALIMBAWA",
  receiptDocTitle: "Resibo ng kahandaan ng aplikasyon",
  receiptGenerated: "Ginawa noong {date}",
  receiptFileLabel: "File",
  receiptSecDocs: "Mga dokumentong naibigay",
  receiptSecIncome: "Pagkalkula ng kita",
  receiptSecReadiness: "Kahandaan ng file",
  receiptEditNote: "Ang mga pagwawasto rito ay agad na nag-a-update sa buong file mo.",
  invalidAmount: "Maglagay ng numerong hindi negatibo, tulad ng 1250.00.",
  receiptFooter:
    "Inihanda ng RealDoor ang buod na ito para tumulong sa isang taong tagasuri. Hindi nito masasabi kung kwalipikado ka — inilalarawan lang ng kahandaan ang mga papeles. Download lang: hindi kailanman ipinapadala ang resibong ito.",
};

const vi: Partial<Copy> = {
  appTitle: "Hồ sơ của bạn",
  appSubtitle: "RealDoor chuẩn bị và kiểm tra giấy tờ của bạn. Không bao giờ quyết định điều kiện.",
  getStarted: "Bắt đầu",
  step1: "Hồ sơ", step2: "Tìm hiểu", step3: "Chuẩn bị",
  step1Info: "Tải lên & xác nhận", step2Info: "Thu nhập & quy định", step3Info: "Kiểm tra & xuất",
  stepLockedNote: "Hoàn thành bước trước đã",
  back: "Quay lại", next: "Tiếp theo", continue: "Tiếp tục",
  statusLabel: "Trạng thái", incomeLabel: "Tổng thu nhập", errorsLabel: "Lỗi",
  statusEmpty: "Chưa bắt đầu", statusReady: "Sẵn sàng xem xét", statusNeeds: "Cần xem xét",
  statusAwaiting: "{n} giá trị cần bạn xác nhận",
  statusIssues: "Cần xem xét · {n} mục cần xử lý",
  statusMissingDocs: "Sẵn sàng xem xét · vẫn còn thiếu giấy tờ",
  statusLocked: "Đã khóa · sẵn sàng xem xét",
  errorsMenuTitle: "Những mục cần chú ý",
  errLowConfidence: "Độ tin cậy thấp — hãy kiểm tra giá trị này",
  uploadTitle: "Tải lên giấy tờ của bạn", chooseFiles: "Chọn tệp", reading: "Đang đọc giấy tờ của bạn…",
  checklistTitle: "Danh sách giấy tờ", present: "Đã tải lên", missing: "Vẫn còn thiếu",
  reviewTitle: "Xác nhận thông tin của bạn", confirm: "Xác nhận", correct: "Sửa", saveCorrection: "Lưu",
  cancel: "Hủy", confidence: "Độ tin cậy", source: "Nguồn", whyNeeded: "Vì sao cần thông tin này",
  understandTitle: "Tìm hiểu thu nhập và quy định", annualizedIncome: "Tổng thu nhập theo năm",
  threshold60: "Giới hạn thu nhập 60% (FY2026)", comparison: "So sánh",
  cmpBelow: "Bằng hoặc thấp hơn giới hạn", cmpAbove: "Cao hơn giới hạn",
  notDecision: "Điều này so sánh thu nhập của bạn với giới hạn đã công bố — không phải quyết định điều kiện.",
  rulesTitle: "Hỏi về các quy định", ask: "Hỏi",
  refusal: "RealDoor không thể cho biết bạn có đủ điều kiện hay không, hay bạn sẽ được chấp thuận hoặc bị từ chối — đó là các quyết định của con người. Nó chỉ chuẩn bị, kiểm tra giấy tờ và so sánh thu nhập với một giới hạn đã công bố.",
  prepareTitle: "Chuẩn bị và hoàn tất", readinessTitle: "Mức độ sẵn sàng của hồ sơ",
  verdictNote: "Điều này mô tả mức độ đầy đủ và nhất quán của hồ sơ — không bao giờ là điều kiện.",
  prepareIntro:
    "Kiểm tra biên nhận bên dưới — sửa những mục được đánh dấu đỏ, sau đó lưu thành PDF hoặc tải gói dữ liệu.",
  editBtn: "Chỉnh sửa thông tin", downloadBtn: "Tải gói hồ sơ",
  deleteBtn: "Xóa phiên", lockBtn: "Xác nhận — khóa là sẵn sàng xem xét",
  deleteConfirm: "Xóa mọi thứ trong phiên này? Giấy tờ, các giá trị đã trích xuất và biên nhận này sẽ bị xóa.",
  receiptTitle: "Biên nhận mức độ sẵn sàng của bạn",
  receiptPrint: "Lưu biên nhận dưới dạng PDF",
  rawShow: "Xem dữ liệu thô", rawHide: "Ẩn dữ liệu thô",
  sampleWord: "BẢN MẪU",
  sampleBanner:
    "Đây là tài liệu BẢN MẪU được tạo từ dữ liệu phiên của bạn. Nó không phải là biểu mẫu chính thức và không bao giờ được gửi đi đâu.",
  receiptKicker: "Giấy tờ nhà ở giá phải chăng · Boston · BẢN MẪU",
  receiptDocTitle: "Biên nhận mức độ sẵn sàng của hồ sơ",
  receiptGenerated: "Tạo ngày {date}",
  receiptFileLabel: "Hồ sơ",
  receiptSecDocs: "Giấy tờ đã cung cấp",
  receiptSecIncome: "Tính toán thu nhập",
  receiptSecReadiness: "Mức độ sẵn sàng của hồ sơ",
  receiptEditNote: "Các chỉnh sửa tại đây sẽ cập nhật toàn bộ hồ sơ của bạn ngay lập tức.",
  invalidAmount: "Nhập một số không âm, ví dụ 1250.00.",
  receiptFooter:
    "RealDoor chuẩn bị bản tóm tắt này để hỗ trợ người xét duyệt. Nó không thể cho bạn biết bạn có đủ điều kiện hay không — mức độ sẵn sàng chỉ mô tả giấy tờ. Chỉ để tải xuống: biên nhận này không bao giờ được truyền đi.",
};

const OVERRIDES: Record<Language, Partial<Copy>> = { en, es, zh, tl, vi };

// Field explanations (EN only; fall back gracefully). Keyed by field name.
export const FIELD_EXPLAIN: Record<string, string> = {
  person_name: "Your name, as it appears on the application, so the file is attributed correctly.",
  household_size: "Household size sets which income limit applies — it drives the threshold in Understand.",
  address: "The address on your application summary; used only to attach documents to the right file.",
  application_date: "When the application was prepared.",
  gross_pay: "Gross pay per period — annualized by its frequency to estimate yearly income.",
  pay_frequency: "How often you're paid; it sets the annualizing multiplier.",
  hourly_rate: "Hourly rate — cross-checked against gross pay for internal consistency.",
  regular_hours: "Hours per period — cross-checked against gross pay.",
  pay_date: "The pay date; the most recent stub from a source is used.",
  document_date: "The letter's date; it must fall within the 60-day currency window.",
  weekly_hours: "Weekly hours stated by the employer.",
  monthly_benefit: "Monthly benefit amount — annualized as recurring income.",
  benefit_frequency: "How often the benefit is paid.",
  gross_receipts: "Gross gig receipts — included as income (×12) and flagged for corroboration.",
  platform_fees: "Platform fees, shown for context; gross receipts drive the income figure.",
  statement_month: "The month this gig statement covers.",
};

export function useCopy(): Copy {
  const { language } = useI18n();
  return { ...en, ...(OVERRIDES[language] ?? {}) };
}

export function fmt(template: string, vars: Record<string, string | number>): string {
  return template.replace(/\{(\w+)\}/g, (_, k) => String(vars[k] ?? `{${k}}`));
}
