"use client";

// Pipeline copy, localized. Every supported language carries EVERY key — the
// `Copy` type on each language block makes a missing key a compile error, so no
// language can silently fall back to English. Kept separate from
// dictionaries.ts to avoid churn on that actively-developed file; can be folded
// in later. Voice: calm, plain, non-decisional — in every language.

import { useI18n } from "@/lib/i18n";
import type { Language } from "@/lib/dictionaries";

const en = {
  appTitle: "Your application",
  appSubtitle: "RealDoor prepares and checks your paperwork for affordable housing in Boston. It never decides eligibility.",
  getStarted: "Get started",
  step1: "Profile",
  step2: "Understand",
  step3: "Prepare",
  step1Info: "Upload & confirm",
  step2Info: "Income & rules",
  step3Info: "Check & export",
  stepLockedNote: "Finish the previous step first",
  back: "Back",
  next: "Next",
  continue: "Continue",

  statusLabel: "Status",
  incomeLabel: "Gross income",
  errorsLabel: "Errors",
  statusEmpty: "Not started",
  statusProfile: "Profile · in progress",
  statusUnderstand: "Understand · in progress",
  statusPrepare: "Prepare · in progress",
  statusReady: "Ready to review",
  statusNeeds: "Needs review",
  statusAwaiting: "{n} values need your confirmation",
  statusIssues: "Needs review · {n} to resolve",
  statusMissingDocs: "Ready to review · documents still missing",
  statusLocked: "Locked · ready to review",
  errorsMenuTitle: "What needs attention",
  errLowConfidence: "Low confidence — check this value",

  uploadTitle: "Upload your documents",
  uploadHint: "Drag PDFs here, or choose files — pay stubs, benefit or employment letters, your application summary.",
  chooseFiles: "Choose files",
  reading: "Reading your documents…",
  noDocs: "No documents yet. Upload one to begin.",
  checklistTitle: "Documents checklist",
  present: "Uploaded",
  missing: "Still missing",

  docApplication_summary: "Application summary",
  docPay_stub: "Pay stub",
  docEmployment_letter: "Employment letter",
  docBenefit_letter: "Benefit letter",
  docGig_statement: "Gig statement",
  docUnknown: "Document",

  reviewTitle: "Confirm your details",
  reviewHint: "Check each value against its source, then confirm it or type a correction. Only confirmed values are used later.",
  fieldOf: "Field {n} of {total}",
  confirm: "Confirm",
  correct: "Correct",
  saveCorrection: "Save",
  cancel: "Cancel",
  confidence: "Confidence",
  stRenterEntered: "Entered by you",
  errNegative: "Error: the amount cannot be negative.",
  dismiss: "Dismiss",
  stExtracted: "Needs your check",
  stConfirmed: "Confirmed",
  stCorrected: "Corrected",
  source: "Source",
  page: "Page {n}",
  openDocument: "Open original document",
  whyNeeded: "Why this is needed",
  fieldExplainFallback: "{field} — extracted from {doc}.",
  allConfirmed: "All values confirmed.",
  goUnderstand: "Continue to Understand",

  quarantineTitle: "Quarantined text — ignored",
  quarantineHint:
    "This document contained instructions aimed at the assistant. RealDoor ignores embedded instructions; the text is shown only for transparency and is never used as data.",

  understandTitle: "Understand your income and the rules",
  incomeCalcTitle: "Annualized income",
  householdSize: "Household size",
  annualizedIncome: "Annualized gross income",
  threshold60: "FY2026 60% income limit",
  comparison: "Comparison",
  cmpBelow: "At or below the published limit",
  cmpAbove: "Above the published limit",
  cmpNone: "No frozen threshold for this household size",
  effective: "Effective",
  notDecision: "This compares your income to a published limit — it is not an eligibility decision.",
  confirmSizeNote: "Confirm the household size in Profile for an exact threshold.",
  formulaHead: "How this was calculated",
  sourcesHead: "Income sources",
  srcCorroborates: "corroborates the same source — not added",
  viewerLabel: "Document viewer",
  zoomIn: "Zoom in",
  zoomOut: "Zoom out",
  zoomFit: "Fit width",
  pageOfTotal: "Page {n} of {total}",
  snapToField: "Snap to value",
  previewError: "The document preview could not be shown. Use the link below to open the original.",
  sampleQ1: "What is the 60% income limit for a household of four?",
  sampleQ2: "When do the FY2026 income limits take effect?",
  sampleQ3: "How is recurring income annualized?",
  sampleQ4: "What makes a file ready to review?",
  mathPerPeriod: "Per period",
  mathPeriodsYr: "Periods / year",
  mathCalc: "Calculation",
  mathPerYear: "Per year",
  mathTotal: "Total",
  srcPay: "Pay",
  srcBenefit: "Benefit",
  srcGig: "Gig receipts",
  freqWeekly: "weekly",
  freqBiweekly: "biweekly",
  freqSemimonthly: "semimonthly",
  freqMonthly: "monthly",
  freqAnnual: "annual",

  rulesTitle: "Ask about the rules",
  rulesHint: "Answers come only from the frozen rule corpus, each with its citation.",
  askPlaceholder: "e.g. What is the 60% limit for a household of four?",
  ask: "Ask",
  tryAsking: "Try asking",
  answerIntro: "From the rule corpus:",
  aiSources: "Sources",
  aiGuideLabel: "RealDoor guide",
  aiCurrentDocument: "Current document",
  aiOutcomeAnswered: "Answered",
  aiOutcomeRefused: "Refused",
  aiOutcomeAbstained: "Abstained",
  aiOutcomeNeedsConfirmation: "Needs confirmation",
  aiOutcomeOutOfScope: "Out of scope",
  authOfficialHud: "Official · HUD",
  authOfficialFederal: "Official · Federal",
  authChallenge: "Challenge convention",
  abstain:
    "I can only answer from the frozen rule corpus and didn't find a matching rule. Try asking about income limits, the effective date, annualizing income, or readiness.",
  refusal:
    "RealDoor can't tell you whether you qualify, or whether you'll be approved or denied — those remain human decisions. It only prepares and checks your paperwork and compares income to a published limit.",
  aiThinking: "Checking sources…",
  aiPrivacy:
    "AI privacy: only confirmed numeric values, statuses, and source references are sent — never your files, raw document text, name, address, or filename. Avoid typing personal details in the question.",
  aiFallback: "The live AI guide was unavailable, so RealDoor used its local frozen-rule fallback.",

  prepareTitle: "Prepare and finish",
  readinessTitle: "File readiness",
  verdictNote: "This describes the file's completeness and consistency — never eligibility.",
  reasonsTitle: "What to resolve",
  noReasons: "Everything checks out — the file is complete and consistent.",
  prepareIntro: "Correct anything marked in red, then save your receipt as a PDF.",
  rc_PAY_STUB_TOTAL_CONFLICT: "A pay stub's stated gross doesn't match its hourly rate × hours.",
  rc_GIG_INCOME_UNCORROBORATED: "Gig income is included but needs corroboration.",
  rc_EMPLOYMENT_LETTER_EXPIRED: "An employment letter is older than the 60-day currency window.",
  rc_UNCONFIRMED_FIELDS: "Some fields still need your confirmation.",
  rc_LOW_CONFIDENCE_FIELDS: "Some fields were extracted with low confidence.",
  rc_BENEFIT_LETTER_EXPIRED: "A benefit letter is older than the 60-day currency window.",
  rc_PAY_STUB_EXPIRED: "A pay stub is older than the 60-day currency window.",
  rc_GIG_STATEMENT_EXPIRED: "A gig statement is older than the 60-day currency window.",
  rc_EMPLOYMENT_RATE_CONFLICT: "The employer letter states a different hourly rate than the pay stub.",
  rc_MISSING_HOUSEHOLD_SIZE: "No documented household size — the frozen threshold table cannot be applied.",
  rc_MISSING_INCOME_EVIDENCE: "No documented recurring income evidence was found.",
  rc_NO_FROZEN_THRESHOLD: "The household size is outside the frozen 1–8 table; no frozen threshold exists.",
  rc_UNVERIFIED_INCOME_CLAIM: "A self-declared income amount has no supporting evidence and was not counted.",
  rcTitle_BENEFIT_LETTER_EXPIRED: "Benefit letter expired",
  rcTitle_PAY_STUB_EXPIRED: "Pay stub expired",
  rcTitle_GIG_STATEMENT_EXPIRED: "Gig statement expired",
  rcTitle_EMPLOYMENT_RATE_CONFLICT: "Hourly rate conflict",
  rcTitle_MISSING_HOUSEHOLD_SIZE: "Household size missing",
  rcTitle_MISSING_INCOME_EVIDENCE: "Income evidence missing",
  rcTitle_NO_FROZEN_THRESHOLD: "No frozen threshold",
  rcTitle_UNVERIFIED_INCOME_CLAIM: "Self-declared income unverified",
  rc_MISSING_REQUIRED_DOCUMENT: "A recommended document hasn't been uploaded yet.",
  rcTitle_PAY_STUB_TOTAL_CONFLICT: "Pay stub totals conflict",
  rcTitle_GIG_INCOME_UNCORROBORATED: "Gig income uncorroborated",
  rcTitle_EMPLOYMENT_LETTER_EXPIRED: "Employment letter expired",
  rcTitle_UNCONFIRMED_FIELDS: "Unconfirmed fields",
  rcTitle_LOW_CONFIDENCE_FIELDS: "Low-confidence fields",
  rcTitle_MISSING_REQUIRED_DOCUMENT: "Missing recommended document",
  editBtn: "Edit details",
  downloadBtn: "Download packet",
  deleteBtn: "Delete session",
  deleteConfirm: "Delete everything in this session? Documents, extracted values, and this receipt will be removed.",
  deletedProof: "Session deleted. {docs} documents and {fields} values removed at {at}.",
  lockBtn: "Confirm — lock as ready to review",
  unlockBtn: "Unlock to edit",
  lockedNote: "Locked as ready to review. You can unlock to edit.",
  fieldsConfirmed: "{n} of {total} fields confirmed",

  receiptTitle: "Your readiness receipt",
  receiptPrint: "Save receipt as PDF",
  rawShow: "View raw data",
  rawHide: "Hide raw data",
  sampleWord: "SAMPLE",
  sampleBanner:
    "This is a SAMPLE document generated from your session data. It is not an official form and is never sent anywhere.",
  receiptKicker: "Affordable housing paperwork · Boston · SAMPLE",
  receiptDocTitle: "Application readiness receipt",
  receiptGenerated: "Generated {date}",
  receiptFileLabel: "File",
  receiptSecDocs: "Documents provided",
  receiptSecIncome: "Income calculation",
  receiptSecReadiness: "File readiness",
  receiptEditNote: "Corrections here update your whole file instantly.",
  invalidAmount: "Enter a non-negative number, like 1250.00.",
  receiptFooter:
    "RealDoor prepared this summary to help a human reviewer. It can't tell you whether you qualify — readiness describes the paperwork only. Download-only: this receipt is never transmitted.",
};

export type Copy = typeof en;

const es: Copy = {
  appTitle: "Tu solicitud",
  appSubtitle: "RealDoor prepara y revisa tus documentos para vivienda asequible en Boston. Nunca decide la elegibilidad.",
  getStarted: "Empezar",
  step1: "Perfil", step2: "Entender", step3: "Preparar",
  step1Info: "Subir y confirmar", step2Info: "Ingresos y reglas", step3Info: "Revisar y exportar",
  stepLockedNote: "Completa primero el paso anterior",
  back: "Atrás", next: "Siguiente", continue: "Continuar",
  statusLabel: "Estado", incomeLabel: "Ingreso bruto", errorsLabel: "Errores",
  statusEmpty: "Sin empezar",
  statusProfile: "Perfil · en curso",
  statusUnderstand: "Entender · en curso",
  statusPrepare: "Preparar · en curso",
  statusReady: "Listo para revisar", statusNeeds: "Necesita revisión",
  statusAwaiting: "{n} valores necesitan tu confirmación",
  statusIssues: "Necesita revisión · {n} por resolver",
  statusMissingDocs: "Listo para revisar · aún faltan documentos",
  statusLocked: "Bloqueado · listo para revisar",
  errorsMenuTitle: "Qué necesita atención",
  errLowConfidence: "Confianza baja — revisa este valor",
  uploadTitle: "Sube tus documentos",
  uploadHint:
    "Arrastra tus PDF aquí o elige archivos — talones de pago, cartas de beneficios o de empleo, tu resumen de solicitud.",
  chooseFiles: "Elegir archivos", reading: "Leyendo tus documentos…",
  noDocs: "Aún no hay documentos. Sube uno para empezar.",
  checklistTitle: "Lista de documentos", present: "Subido", missing: "Aún falta",
  docApplication_summary: "Resumen de solicitud",
  docPay_stub: "Talón de pago",
  docEmployment_letter: "Carta de empleo",
  docBenefit_letter: "Carta de beneficios",
  docGig_statement: "Estado de cuenta gig",
  docUnknown: "Documento",
  reviewTitle: "Confirma tus datos",
  reviewHint:
    "Compara cada valor con su fuente y luego confírmalo o escribe una corrección. Solo los valores confirmados se usan después.",
  fieldOf: "Campo {n} de {total}",
  confirm: "Confirmar", correct: "Corregir", saveCorrection: "Guardar",
  cancel: "Cancelar", confidence: "Confianza",
  stRenterEntered: "Ingresado por ti",
  errNegative: "Error: el importe no puede ser negativo.",
  dismiss: "Cerrar",
  stExtracted: "Requiere tu revisión", stConfirmed: "Confirmado", stCorrected: "Corregido",
  source: "Fuente",
  page: "Página {n}",
  openDocument: "Abrir el documento original",
  whyNeeded: "Por qué se necesita",
  fieldExplainFallback: "{field} — extraído de {doc}.",
  allConfirmed: "Todos los valores confirmados.",
  goUnderstand: "Continuar a Entender",
  quarantineTitle: "Texto en cuarentena — ignorado",
  quarantineHint:
    "Este documento contenía instrucciones dirigidas al asistente. RealDoor ignora las instrucciones incrustadas; el texto se muestra solo por transparencia y nunca se usa como datos.",
  understandTitle: "Entiende tus ingresos y las reglas",
  incomeCalcTitle: "Ingreso anualizado",
  householdSize: "Tamaño del hogar",
  annualizedIncome: "Ingreso bruto anualizado",
  srcCorroborates: "corrobora la misma fuente — no se suma",
  viewerLabel: "Visor de documentos",
  zoomIn: "Acercar",
  zoomOut: "Alejar",
  zoomFit: "Ajustar al ancho",
  pageOfTotal: "Página {n} de {total}",
  snapToField: "Ir al valor",
  previewError: "No se pudo mostrar la vista previa del documento. Usa el enlace de abajo para abrir el original.",
  sampleQ1: "¿Cuál es el límite de ingresos del 60% para un hogar de cuatro?",
  sampleQ2: "¿Cuándo entran en vigor los límites de ingresos del FY2026?",
  sampleQ3: "¿Cómo se anualizan los ingresos recurrentes?",
  sampleQ4: "¿Qué hace que un expediente esté listo para revisar?",
  mathPerPeriod: "Por período",
  mathPeriodsYr: "Períodos al año",
  mathCalc: "Cálculo",
  mathPerYear: "Al año",
  mathTotal: "Total",
  srcPay: "Salario",
  srcBenefit: "Beneficio",
  srcGig: "Ingresos gig",
  aiThinking: "Consultando las fuentes…",
  aiPrivacy:
    "Privacidad de la IA: solo se envían valores numéricos confirmados, estados y referencias de fuente — nunca tus archivos, el texto de los documentos, tu nombre, dirección ni nombres de archivo. Evita escribir datos personales en la pregunta.",
  aiFallback: "El guía de IA en vivo no estaba disponible; RealDoor usó su respaldo local de reglas congeladas.",
  freqWeekly: "semanal", freqBiweekly: "cada dos semanas", freqSemimonthly: "dos veces al mes",
  freqMonthly: "mensual", freqAnnual: "anual",
  threshold60: "Límite de ingresos del 60% (FY2026)", comparison: "Comparación",
  cmpBelow: "Igual o por debajo del límite", cmpAbove: "Por encima del límite",
  cmpNone: "No hay límite congelado para este tamaño de hogar",
  effective: "Vigente desde",
  notDecision: "Esto compara tus ingresos con un límite publicado — no es una decisión de elegibilidad.",
  confirmSizeNote: "Confirma el tamaño del hogar en Perfil para un límite exacto.",
  formulaHead: "Cómo se calculó",
  sourcesHead: "Fuentes de ingresos",
  rulesTitle: "Pregunta sobre las reglas",
  rulesHint: "Las respuestas provienen solo del corpus de reglas congelado, cada una con su cita.",
  askPlaceholder: "p. ej. ¿Cuál es el límite del 60% para un hogar de cuatro?",
  ask: "Preguntar",
  tryAsking: "Prueba preguntar",
  answerIntro: "Del corpus de reglas:",
  aiSources: "Fuentes",
  aiGuideLabel: "Guía de RealDoor",
  aiCurrentDocument: "Documento actual",
  aiOutcomeAnswered: "Respondido",
  aiOutcomeRefused: "Rehusado",
  aiOutcomeAbstained: "Se abstuvo",
  aiOutcomeNeedsConfirmation: "Necesita confirmación",
  aiOutcomeOutOfScope: "Fuera de alcance",
  authOfficialHud: "Oficial · HUD",
  authOfficialFederal: "Oficial · Federal",
  authChallenge: "Convención del reto",
  abstain:
    "Solo puedo responder desde el corpus de reglas congelado y no encontré una regla que coincida. Prueba preguntar sobre los límites de ingresos, la fecha de vigencia, la anualización de ingresos o la preparación del expediente.",
  refusal: "RealDoor no puede decirte si cumples los requisitos, ni si serás aprobado o rechazado — esas son decisiones humanas. Solo prepara y revisa tus documentos y compara los ingresos con un límite publicado.",
  prepareTitle: "Prepara y finaliza", readinessTitle: "Preparación del expediente",
  verdictNote: "Describe qué tan completo y coherente está el expediente — nunca la elegibilidad.",
  reasonsTitle: "Qué resolver",
  noReasons: "Todo está en orden — el expediente está completo y es coherente.",
  prepareIntro:
    "Revisa tu recibo abajo — corrige lo marcado en rojo y luego guárdalo como PDF o descarga el paquete de datos.",
  rcTitle_PAY_STUB_TOTAL_CONFLICT: "Conflicto en los totales del recibo de pago",
  rcTitle_GIG_INCOME_UNCORROBORATED: "Ingresos por plataforma sin corroborar",
  rcTitle_EMPLOYMENT_LETTER_EXPIRED: "Carta de empleo vencida",
  rcTitle_UNCONFIRMED_FIELDS: "Campos sin confirmar",
  rcTitle_LOW_CONFIDENCE_FIELDS: "Campos con baja confianza",
  rcTitle_MISSING_REQUIRED_DOCUMENT: "Falta un documento recomendado",
  rc_PAY_STUB_TOTAL_CONFLICT: "El bruto declarado de un talón de pago no coincide con su tarifa por hora × horas.",
  rc_GIG_INCOME_UNCORROBORATED: "Los ingresos gig están incluidos pero necesitan corroboración.",
  rc_EMPLOYMENT_LETTER_EXPIRED: "Una carta de empleo es más antigua que la ventana de vigencia de 60 días.",
  rc_UNCONFIRMED_FIELDS: "Algunos campos aún necesitan tu confirmación.",
  rc_LOW_CONFIDENCE_FIELDS: "Algunos campos se extrajeron con confianza baja.",
  rc_BENEFIT_LETTER_EXPIRED: "Una carta de beneficios supera la ventana de vigencia de 60 días.",
  rc_PAY_STUB_EXPIRED: "Un recibo de pago supera la ventana de vigencia de 60 días.",
  rc_GIG_STATEMENT_EXPIRED: "Un estado de ingresos gig supera la ventana de vigencia de 60 días.",
  rc_EMPLOYMENT_RATE_CONFLICT: "La carta del empleador indica una tarifa por hora distinta a la del recibo de pago.",
  rc_MISSING_HOUSEHOLD_SIZE: "No hay tamaño del hogar documentado — no se puede aplicar la tabla de límites congelada.",
  rc_MISSING_INCOME_EVIDENCE: "No se encontró evidencia documentada de ingresos recurrentes.",
  rc_NO_FROZEN_THRESHOLD: "El tamaño del hogar está fuera de la tabla congelada de 1–8; no existe límite congelado.",
  rc_UNVERIFIED_INCOME_CLAIM: "Un ingreso autodeclarado no tiene evidencia de respaldo y no se contó.",
  rcTitle_BENEFIT_LETTER_EXPIRED: "Carta de beneficios vencida",
  rcTitle_PAY_STUB_EXPIRED: "Recibo de pago vencido",
  rcTitle_GIG_STATEMENT_EXPIRED: "Estado gig vencido",
  rcTitle_EMPLOYMENT_RATE_CONFLICT: "Conflicto de tarifa por hora",
  rcTitle_MISSING_HOUSEHOLD_SIZE: "Falta el tamaño del hogar",
  rcTitle_MISSING_INCOME_EVIDENCE: "Falta evidencia de ingresos",
  rcTitle_NO_FROZEN_THRESHOLD: "Sin límite congelado",
  rcTitle_UNVERIFIED_INCOME_CLAIM: "Ingreso autodeclarado sin verificar",
  rc_MISSING_REQUIRED_DOCUMENT: "Un documento recomendado aún no se ha subido.",
  editBtn: "Editar datos", downloadBtn: "Descargar paquete",
  deleteBtn: "Borrar sesión", lockBtn: "Confirmar — marcar como listo para revisar",
  unlockBtn: "Desbloquear para editar",
  lockedNote: "Bloqueado como listo para revisar. Puedes desbloquear para editar.",
  deleteConfirm: "¿Borrar todo en esta sesión? Se eliminarán los documentos, los valores extraídos y este recibo.",
  deletedProof: "Sesión borrada. {docs} documentos y {fields} valores eliminados el {at}.",
  fieldsConfirmed: "{n} de {total} campos confirmados",
  receiptTitle: "Tu recibo de preparación",
  receiptPrint: "Guardar recibo como PDF",
  rawShow: "Ver datos sin procesar", rawHide: "Ocultar datos sin procesar",
  sampleWord: "MUESTRA",
  sampleBanner:
    "Este es un documento de MUESTRA generado con los datos de tu sesión. No es un formulario oficial y nunca se envía a ninguna parte.",
  receiptKicker: "Documentos de vivienda asequible · Boston · MUESTRA",
  receiptDocTitle: "Recibo de preparación de la solicitud",
  receiptGenerated: "Generado el {date}",
  receiptFileLabel: "Expediente",
  receiptSecDocs: "Documentos entregados",
  receiptSecIncome: "Cálculo de ingresos",
  receiptSecReadiness: "Preparación del expediente",
  receiptEditNote: "Las correcciones aquí actualizan todo tu expediente al instante.",
  invalidAmount: "Introduce un número no negativo, como 1250.00.",
  receiptFooter:
    "RealDoor preparó este resumen para ayudar a un revisor humano. No puede decirte si cumples los requisitos — la preparación describe solo los documentos. Solo descarga: este recibo nunca se transmite.",
};

const zh: Copy = {
  appTitle: "您的申请",
  appSubtitle: "RealDoor 帮您准备并核对波士顿可负担住房的申请材料，绝不判定资格。",
  getStarted: "开始",
  step1: "个人资料", step2: "了解", step3: "准备",
  step1Info: "上传并确认", step2Info: "收入与规则", step3Info: "检查并导出",
  stepLockedNote: "请先完成上一步",
  back: "返回", next: "下一步", continue: "继续",
  statusLabel: "状态", incomeLabel: "总收入", errorsLabel: "错误",
  statusEmpty: "未开始",
  statusProfile: "个人资料 · 进行中",
  statusUnderstand: "了解 · 进行中",
  statusPrepare: "准备 · 进行中",
  statusReady: "可供审核", statusNeeds: "需要复核",
  statusAwaiting: "{n} 项信息待您确认",
  statusIssues: "需要复核 · {n} 项待解决",
  statusMissingDocs: "可供审核 · 仍缺少文件",
  statusLocked: "已锁定 · 可供审核",
  errorsMenuTitle: "需要处理的事项",
  errLowConfidence: "置信度低——请核对此值",
  uploadTitle: "上传您的文件",
  uploadHint: "将 PDF 拖到此处或选择文件——工资单、福利或在职证明信、您的申请摘要。",
  chooseFiles: "选择文件", reading: "正在读取您的文件…",
  noDocs: "还没有文件。上传一份即可开始。",
  checklistTitle: "文件清单", present: "已上传", missing: "仍缺少",
  docApplication_summary: "申请摘要",
  docPay_stub: "工资单",
  docEmployment_letter: "在职证明信",
  docBenefit_letter: "福利信",
  docGig_statement: "零工对账单",
  docUnknown: "文件",
  reviewTitle: "确认您的信息",
  reviewHint: "将每个数值与其来源核对，然后确认或输入更正。之后只使用已确认的数值。",
  fieldOf: "第 {n} 项，共 {total} 项",
  confirm: "确认", correct: "更正", saveCorrection: "保存",
  cancel: "取消", confidence: "置信度",
  stRenterEntered: "由您输入",
  errNegative: "错误：金额不能为负数。",
  dismiss: "关闭",
  stExtracted: "待您核对", stConfirmed: "已确认", stCorrected: "已更正",
  source: "来源",
  page: "第 {n} 页",
  openDocument: "打开原始文件",
  whyNeeded: "为何需要",
  fieldExplainFallback: "{field}——提取自{doc}。",
  allConfirmed: "所有数值均已确认。",
  goUnderstand: "继续前往“了解”",
  quarantineTitle: "已隔离的文字——已忽略",
  quarantineHint:
    "此文件包含针对助手的指令。RealDoor 会忽略嵌入的指令；文字仅为透明起见显示，绝不会用作数据。",
  understandTitle: "了解您的收入与规则",
  incomeCalcTitle: "年化收入",
  householdSize: "家庭人数",
  annualizedIncome: "年化总收入",
  srcCorroborates: "佐证同一来源——不重复计入",
  viewerLabel: "文件查看器",
  zoomIn: "放大",
  zoomOut: "缩小",
  zoomFit: "适应宽度",
  pageOfTotal: "第 {n} 页，共 {total} 页",
  snapToField: "定位到数值",
  previewError: "无法显示文件预览。请使用下方链接打开原件。",
  sampleQ1: "四口之家的 60% 收入上限是多少？",
  sampleQ2: "2026 财年收入上限何时生效？",
  sampleQ3: "经常性收入如何年化？",
  sampleQ4: "什么情况下材料可供审核？",
  mathPerPeriod: "每期",
  mathPeriodsYr: "每年期数",
  mathCalc: "计算",
  mathPerYear: "每年",
  mathTotal: "合计",
  srcPay: "工资",
  srcBenefit: "福利",
  srcGig: "零工收入",
  aiThinking: "正在核对来源…",
  aiPrivacy:
    "AI 隐私：仅发送已确认的数值、状态和来源引用——绝不发送您的文件、文档原文、姓名、地址或文件名。请避免在问题中输入个人信息。",
  aiFallback: "在线 AI 助手不可用，RealDoor 已使用本地冻结规则备用方案。",
  freqWeekly: "每周", freqBiweekly: "每两周", freqSemimonthly: "每半月",
  freqMonthly: "每月", freqAnnual: "每年",
  threshold60: "2026 财年 60% 收入上限", comparison: "比较",
  cmpBelow: "等于或低于上限", cmpAbove: "高于上限",
  cmpNone: "此家庭人数没有冻结的上限",
  effective: "生效日期",
  notDecision: "这是将您的收入与公布上限比较——并非资格判定。",
  confirmSizeNote: "请在“个人资料”中确认家庭人数以获得准确上限。",
  formulaHead: "计算方式",
  sourcesHead: "收入来源",
  rulesTitle: "咨询相关规则",
  rulesHint: "回答仅来自冻结的规则库，每条均附引用。",
  askPlaceholder: "例如：四口之家的 60% 上限是多少？",
  ask: "提问",
  tryAsking: "试试提问",
  answerIntro: "来自规则库：",
  aiSources: "来源",
  aiGuideLabel: "RealDoor 指南",
  aiCurrentDocument: "当前文件",
  aiOutcomeAnswered: "已回答",
  aiOutcomeRefused: "已拒答",
  aiOutcomeAbstained: "未作答",
  aiOutcomeNeedsConfirmation: "需要确认",
  aiOutcomeOutOfScope: "超出范围",
  authOfficialHud: "官方 · HUD",
  authOfficialFederal: "官方 · 联邦",
  authChallenge: "挑战赛约定",
  abstain:
    "我只能根据冻结的规则库回答，未找到匹配的规则。可以试试询问收入上限、生效日期、收入年化或材料就绪情况。",
  refusal: "RealDoor 无法告诉您是否符合资格，也无法判定批准或拒绝——这些属于人工决定。它只帮您准备和核对材料，并将收入与公布的上限进行比较。",
  prepareTitle: "准备并完成", readinessTitle: "材料就绪情况",
  verdictNote: "这说明材料的完整性与一致性——绝不涉及资格。",
  reasonsTitle: "需要解决的事项",
  noReasons: "一切正常——材料完整且一致。",
  prepareIntro: "请检查下方的回执——更正标为红色的内容，然后将其保存为 PDF 或下载数据包。",
  rcTitle_PAY_STUB_TOTAL_CONFLICT: "工资单总额不符",
  rcTitle_GIG_INCOME_UNCORROBORATED: "零工收入未经佐证",
  rcTitle_EMPLOYMENT_LETTER_EXPIRED: "雇佣证明信已过期",
  rcTitle_UNCONFIRMED_FIELDS: "字段未确认",
  rcTitle_LOW_CONFIDENCE_FIELDS: "字段置信度低",
  rcTitle_MISSING_REQUIRED_DOCUMENT: "缺少建议文件",
  rc_PAY_STUB_TOTAL_CONFLICT: "一张工资单标注的总额与其时薪 × 工时不符。",
  rc_GIG_INCOME_UNCORROBORATED: "零工收入已计入，但需要佐证。",
  rc_EMPLOYMENT_LETTER_EXPIRED: "一封在职证明信超出了 60 天有效期窗口。",
  rc_UNCONFIRMED_FIELDS: "部分信息仍需您确认。",
  rc_LOW_CONFIDENCE_FIELDS: "部分信息提取时置信度较低。",
  rc_BENEFIT_LETTER_EXPIRED: "一封福利证明信超出了 60 天有效期窗口。",
  rc_PAY_STUB_EXPIRED: "一张工资单超出了 60 天有效期窗口。",
  rc_GIG_STATEMENT_EXPIRED: "一份零工收入单超出了 60 天有效期窗口。",
  rc_EMPLOYMENT_RATE_CONFLICT: "雇主信中注明的时薪与工资单不一致。",
  rc_MISSING_HOUSEHOLD_SIZE: "没有记录在案的家庭人数——无法应用冻结的上限表。",
  rc_MISSING_INCOME_EVIDENCE: "未找到记录在案的经常性收入证明。",
  rc_NO_FROZEN_THRESHOLD: "家庭人数超出冻结的 1–8 人表；不存在冻结上限。",
  rc_UNVERIFIED_INCOME_CLAIM: "自行申报的收入金额没有佐证材料，未被计入。",
  rcTitle_BENEFIT_LETTER_EXPIRED: "福利证明信已过期",
  rcTitle_PAY_STUB_EXPIRED: "工资单已过期",
  rcTitle_GIG_STATEMENT_EXPIRED: "零工收入单已过期",
  rcTitle_EMPLOYMENT_RATE_CONFLICT: "时薪不一致",
  rcTitle_MISSING_HOUSEHOLD_SIZE: "缺少家庭人数",
  rcTitle_MISSING_INCOME_EVIDENCE: "缺少收入证明",
  rcTitle_NO_FROZEN_THRESHOLD: "无冻结上限",
  rcTitle_UNVERIFIED_INCOME_CLAIM: "自报收入未经核实",
  rc_MISSING_REQUIRED_DOCUMENT: "有一份建议提供的文件尚未上传。",
  editBtn: "编辑信息", downloadBtn: "下载材料包",
  deleteBtn: "删除会话", lockBtn: "确认——标记为可供审核",
  unlockBtn: "解锁以编辑",
  lockedNote: "已锁定为可供审核。您可以解锁进行编辑。",
  deleteConfirm: "删除本会话中的所有内容？文件、提取的数值和此回执都将被移除。",
  deletedProof: "会话已删除。已于 {at} 移除 {docs} 份文件和 {fields} 项数值。",
  fieldsConfirmed: "已确认 {n}/{total} 项",
  receiptTitle: "您的就绪回执",
  receiptPrint: "将回执保存为 PDF",
  rawShow: "查看原始数据", rawHide: "隐藏原始数据",
  sampleWord: "样本",
  sampleBanner: "这是根据您的会话数据生成的样本文件。它不是官方表格，也绝不会被发送到任何地方。",
  receiptKicker: "可负担住房材料 · 波士顿 · 样本",
  receiptDocTitle: "申请就绪回执",
  receiptGenerated: "生成于 {date}",
  receiptFileLabel: "档案",
  receiptSecDocs: "已提供的文件",
  receiptSecIncome: "收入计算",
  receiptSecReadiness: "材料就绪情况",
  receiptEditNote: "在此处的更正会立即更新您的整个档案。",
  invalidAmount: "请输入非负数字，例如 1250.00。",
  receiptFooter:
    "RealDoor 准备本摘要以协助人工审核。它无法告诉您是否符合资格——就绪仅描述材料本身。仅供下载：此回执绝不会被传送。",
};

const tl: Copy = {
  appTitle: "Ang iyong aplikasyon",
  appSubtitle: "Inihahanda at sinusuri ng RealDoor ang iyong mga papeles para sa abot-kayang pabahay sa Boston. Hindi ito nagpapasya ng eligibility.",
  getStarted: "Magsimula",
  step1: "Profile", step2: "Unawain", step3: "Maghanda",
  step1Info: "I-upload at kumpirmahin", step2Info: "Kita at patakaran", step3Info: "Suriin at i-export",
  stepLockedNote: "Tapusin muna ang naunang hakbang",
  back: "Bumalik", next: "Susunod", continue: "Magpatuloy",
  statusLabel: "Katayuan", incomeLabel: "Kabuuang kita", errorsLabel: "Mga error",
  statusEmpty: "Hindi pa nagsisimula",
  statusProfile: "Profile · isinasagawa",
  statusUnderstand: "Unawain · isinasagawa",
  statusPrepare: "Maghanda · isinasagawa",
  statusReady: "Handa nang suriin", statusNeeds: "Kailangang suriin",
  statusAwaiting: "{n} na halaga ang kailangang kumpirmahin",
  statusIssues: "Kailangang suriin · {n} ang dapat ayusin",
  statusMissingDocs: "Handa nang suriin · may kulang pang dokumento",
  statusLocked: "Naka-lock · handa nang suriin",
  errorsMenuTitle: "Ano ang kailangang asikasuhin",
  errLowConfidence: "Mababa ang kumpiyansa — suriin ang halagang ito",
  uploadTitle: "I-upload ang iyong mga dokumento",
  uploadHint:
    "I-drag ang mga PDF dito, o pumili ng mga file — mga pay stub, sulat ng benepisyo o ng employer, ang buod ng iyong aplikasyon.",
  chooseFiles: "Pumili ng mga file", reading: "Binabasa ang iyong mga dokumento…",
  noDocs: "Wala pang dokumento. Mag-upload ng isa para magsimula.",
  checklistTitle: "Listahan ng dokumento", present: "Na-upload", missing: "Kulang pa",
  docApplication_summary: "Buod ng aplikasyon",
  docPay_stub: "Pay stub",
  docEmployment_letter: "Sulat ng employer",
  docBenefit_letter: "Sulat ng benepisyo",
  docGig_statement: "Gig statement",
  docUnknown: "Dokumento",
  reviewTitle: "Kumpirmahin ang iyong mga detalye",
  reviewHint:
    "Itugma ang bawat halaga sa pinagmulan nito, pagkatapos ay kumpirmahin ito o mag-type ng pagwawasto. Ang mga kumpirmadong halaga lang ang gagamitin pagkatapos.",
  fieldOf: "Field {n} ng {total}",
  confirm: "Kumpirmahin", correct: "Iwasto", saveCorrection: "I-save",
  cancel: "Kanselahin", confidence: "Kumpiyansa",
  stRenterEntered: "Ikaw ang naglagay",
  errNegative: "Error: hindi maaaring negatibo ang halaga.",
  dismiss: "Isara",
  stExtracted: "Kailangan ng iyong pagsusuri", stConfirmed: "Kumpirmado", stCorrected: "Naiwasto",
  source: "Pinagmulan",
  page: "Pahina {n}",
  openDocument: "Buksan ang orihinal na dokumento",
  whyNeeded: "Bakit kailangan ito",
  fieldExplainFallback: "{field} — na-extract mula sa {doc}.",
  allConfirmed: "Kumpirmado na ang lahat ng halaga.",
  goUnderstand: "Magpatuloy sa Unawain",
  quarantineTitle: "Naka-quarantine na teksto — hindi pinansin",
  quarantineHint:
    "May mga tagubiling nakatuon sa assistant ang dokumentong ito. Hindi pinapansin ng RealDoor ang mga nakapaloob na tagubilin; ipinapakita lang ang teksto para sa transparency at hindi kailanman ginagamit bilang datos.",
  understandTitle: "Unawain ang iyong kita at ang mga patakaran",
  incomeCalcTitle: "Na-annualize na kita",
  householdSize: "Laki ng sambahayan",
  annualizedIncome: "Taunang kabuuang kita",
  srcCorroborates: "nagpapatunay sa parehong source — hindi idinaragdag",
  viewerLabel: "Viewer ng dokumento",
  zoomIn: "I-zoom in",
  zoomOut: "I-zoom out",
  zoomFit: "Iangkop sa lapad",
  pageOfTotal: "Pahina {n} ng {total}",
  snapToField: "Pumunta sa halaga",
  previewError: "Hindi maipakita ang preview ng dokumento. Gamitin ang link sa ibaba para buksan ang orihinal.",
  sampleQ1: "Ano ang 60% na limitasyon sa kita para sa sambahayang apat?",
  sampleQ2: "Kailan magkakabisa ang mga limitasyon sa kita ng FY2026?",
  sampleQ3: "Paano ina-annualize ang paulit-ulit na kita?",
  sampleQ4: "Kailan nagiging handa nang suriin ang isang file?",
  mathPerPeriod: "Bawat period",
  mathPeriodsYr: "Period kada taon",
  mathCalc: "Kalkulasyon",
  mathPerYear: "Kada taon",
  mathTotal: "Kabuuan",
  srcPay: "Sahod",
  srcBenefit: "Benepisyo",
  srcGig: "Kita sa gig",
  aiThinking: "Sinusuri ang mga pinagmulan…",
  aiPrivacy:
    "Privacy ng AI: mga kumpirmadong numerong halaga, status, at sanggunian ng pinagmulan lang ang ipinapadala — hindi kailanman ang iyong mga file, teksto ng dokumento, pangalan, address, o filename. Iwasang mag-type ng personal na detalye sa tanong.",
  aiFallback: "Hindi available ang live na AI guide, kaya ginamit ng RealDoor ang lokal nitong frozen-rule fallback.",
  freqWeekly: "lingguhan", freqBiweekly: "tuwing dalawang linggo", freqSemimonthly: "dalawang beses sa isang buwan",
  freqMonthly: "buwanan", freqAnnual: "taunan",
  threshold60: "FY2026 60% na limitasyon sa kita", comparison: "Paghahambing",
  cmpBelow: "Katumbas o mas mababa sa limitasyon", cmpAbove: "Higit sa limitasyon",
  cmpNone: "Walang frozen na limitasyon para sa laki ng sambahayang ito",
  effective: "May bisa mula",
  notDecision: "Inihahambing nito ang iyong kita sa isang nakalathalang limitasyon — hindi ito desisyon sa eligibility.",
  confirmSizeNote: "Kumpirmahin ang laki ng sambahayan sa Profile para sa eksaktong limitasyon.",
  formulaHead: "Paano ito kinalkula",
  sourcesHead: "Mga pinagmulan ng kita",
  rulesTitle: "Magtanong tungkol sa mga patakaran",
  rulesHint: "Ang mga sagot ay mula lang sa frozen na rule corpus, bawat isa may citation.",
  askPlaceholder: "hal. Ano ang 60% na limitasyon para sa sambahayang apat?",
  ask: "Magtanong",
  tryAsking: "Subukang itanong",
  answerIntro: "Mula sa rule corpus:",
  aiSources: "Mga pinagmulan",
  aiGuideLabel: "Gabay ng RealDoor",
  aiCurrentDocument: "Kasalukuyang dokumento",
  aiOutcomeAnswered: "Nasagot",
  aiOutcomeRefused: "Tumanggi",
  aiOutcomeAbstained: "Hindi sumagot",
  aiOutcomeNeedsConfirmation: "Kailangan ng kumpirmasyon",
  aiOutcomeOutOfScope: "Wala sa saklaw",
  authOfficialHud: "Opisyal · HUD",
  authOfficialFederal: "Opisyal · Pederal",
  authChallenge: "Kumbensyon ng challenge",
  abstain:
    "Makakasagot lang ako mula sa frozen na rule corpus at wala akong nahanap na tumutugmang patakaran. Subukang magtanong tungkol sa mga limitasyon sa kita, petsa ng pagkakabisa, pag-a-annualize ng kita, o kahandaan ng file.",
  refusal: "Hindi masasabi ng RealDoor kung kwalipikado ka, o kung maa-aprubahan o tatanggihan ka — mga desisyon iyon ng tao. Inihahanda at sinusuri lang nito ang iyong mga papeles at inihahambing ang kita sa isang nakalathalang limitasyon.",
  prepareTitle: "Maghanda at tapusin", readinessTitle: "Kahandaan ng file",
  verdictNote: "Inilalarawan nito ang pagkakumpleto at pagkakatugma ng file — hindi ang eligibility.",
  reasonsTitle: "Ano ang dapat ayusin",
  noReasons: "Maayos ang lahat — kumpleto at magkakatugma ang file.",
  prepareIntro:
    "Suriin ang resibo sa ibaba — iwasto ang mga minarkahan ng pula, pagkatapos ay i-save ito bilang PDF o i-download ang data packet.",
  rcTitle_PAY_STUB_TOTAL_CONFLICT: "Magkasalungat ang mga total ng pay stub",
  rcTitle_GIG_INCOME_UNCORROBORATED: "Walang patunay ang kita sa gig",
  rcTitle_EMPLOYMENT_LETTER_EXPIRED: "Paso na ang sulat mula sa employer",
  rcTitle_UNCONFIRMED_FIELDS: "May mga field na hindi pa kumpirmado",
  rcTitle_LOW_CONFIDENCE_FIELDS: "May mga field na mababa ang kumpiyansa",
  rcTitle_MISSING_REQUIRED_DOCUMENT: "May kulang na inirerekomendang dokumento",
  rc_PAY_STUB_TOTAL_CONFLICT: "Hindi tugma ang nakasaad na gross ng isang pay stub sa rate kada oras × oras nito.",
  rc_GIG_INCOME_UNCORROBORATED: "Kasama ang kita sa gig ngunit kailangan pa ng patunay.",
  rc_EMPLOYMENT_LETTER_EXPIRED: "May sulat ng employer na mas luma kaysa sa 60-araw na palugit.",
  rc_UNCONFIRMED_FIELDS: "May mga field na kailangan pa ng iyong kumpirmasyon.",
  rc_LOW_CONFIDENCE_FIELDS: "May mga field na na-extract nang mababa ang kumpiyansa.",
  rc_BENEFIT_LETTER_EXPIRED: "May sulat ng benepisyo na lampas na sa 60-araw na window.",
  rc_PAY_STUB_EXPIRED: "May pay stub na lampas na sa 60-araw na window.",
  rc_GIG_STATEMENT_EXPIRED: "May gig statement na lampas na sa 60-araw na window.",
  rc_EMPLOYMENT_RATE_CONFLICT: "Iba ang rate kada oras na nakasaad sa sulat ng employer kaysa sa pay stub.",
  rc_MISSING_HOUSEHOLD_SIZE: "Walang dokumentadong laki ng sambahayan — hindi magagamit ang nakapirming talaan ng limitasyon.",
  rc_MISSING_INCOME_EVIDENCE: "Walang nahanap na dokumentadong ebidensya ng paulit-ulit na kita.",
  rc_NO_FROZEN_THRESHOLD: "Ang laki ng sambahayan ay wala sa nakapirming talaan na 1–8; walang nakapirming limitasyon.",
  rc_UNVERIFIED_INCOME_CLAIM: "May self-declared na kita na walang suportang ebidensya at hindi ibinilang.",
  rcTitle_BENEFIT_LETTER_EXPIRED: "Paso na ang sulat ng benepisyo",
  rcTitle_PAY_STUB_EXPIRED: "Paso na ang pay stub",
  rcTitle_GIG_STATEMENT_EXPIRED: "Paso na ang gig statement",
  rcTitle_EMPLOYMENT_RATE_CONFLICT: "Salungatan sa rate kada oras",
  rcTitle_MISSING_HOUSEHOLD_SIZE: "Walang laki ng sambahayan",
  rcTitle_MISSING_INCOME_EVIDENCE: "Walang ebidensya ng kita",
  rcTitle_NO_FROZEN_THRESHOLD: "Walang nakapirming limitasyon",
  rcTitle_UNVERIFIED_INCOME_CLAIM: "Hindi beripikado ang self-declared na kita",
  rc_MISSING_REQUIRED_DOCUMENT: "May inirerekomendang dokumento na hindi pa nai-upload.",
  editBtn: "I-edit ang mga detalye", downloadBtn: "I-download ang packet",
  deleteBtn: "Burahin ang session", lockBtn: "Kumpirmahin — i-lock bilang handa nang suriin",
  unlockBtn: "I-unlock para mag-edit",
  lockedNote: "Naka-lock bilang handa nang suriin. Maaari mong i-unlock para mag-edit.",
  deleteConfirm: "Burahin ang lahat sa session na ito? Aalisin ang mga dokumento, mga na-extract na halaga, at ang resibong ito.",
  deletedProof: "Nabura na ang session. {docs} dokumento at {fields} halaga ang inalis noong {at}.",
  fieldsConfirmed: "{n} sa {total} field ang kumpirmado",
  receiptTitle: "Ang iyong resibo ng kahandaan",
  receiptPrint: "I-save ang resibo bilang PDF",
  rawShow: "Tingnan ang raw na datos", rawHide: "Itago ang raw na datos",
  sampleWord: "HALIMBAWA",
  sampleBanner:
    "Ito ay isang HALIMBAWANG dokumento na ginawa mula sa datos ng iyong session. Hindi ito opisyal na form at hindi kailanman ipinapadala kahit saan.",
  receiptKicker: "Mga papeles sa abot-kayang pabahay · Boston · HALIMBAWA",
  receiptDocTitle: "Resibo ng kahandaan ng aplikasyon",
  receiptGenerated: "Ginawa noong {date}",
  receiptFileLabel: "File",
  receiptSecDocs: "Mga dokumentong naibigay",
  receiptSecIncome: "Pagkalkula ng kita",
  receiptSecReadiness: "Kahandaan ng file",
  receiptEditNote: "Ang mga pagwawasto rito ay agad na nag-a-update sa buong file mo.",
  invalidAmount: "Maglagay ng numerong hindi negatibo, tulad ng 1250.00.",
  receiptFooter:
    "Inihanda ng RealDoor ang buod na ito para tumulong sa isang taong tagasuri. Hindi nito masasabi kung kwalipikado ka — inilalarawan lang ng kahandaan ang mga papeles. Download lang: hindi kailanman ipinapadala ang resibong ito.",
};

const vi: Copy = {
  appTitle: "Hồ sơ của bạn",
  appSubtitle: "RealDoor chuẩn bị và kiểm tra giấy tờ của bạn cho nhà ở giá phải chăng tại Boston. Không bao giờ quyết định điều kiện.",
  getStarted: "Bắt đầu",
  step1: "Hồ sơ", step2: "Tìm hiểu", step3: "Chuẩn bị",
  step1Info: "Tải lên & xác nhận", step2Info: "Thu nhập & quy định", step3Info: "Kiểm tra & xuất",
  stepLockedNote: "Hoàn thành bước trước đã",
  back: "Quay lại", next: "Tiếp theo", continue: "Tiếp tục",
  statusLabel: "Trạng thái", incomeLabel: "Tổng thu nhập", errorsLabel: "Lỗi",
  statusEmpty: "Chưa bắt đầu",
  statusProfile: "Hồ sơ · đang thực hiện",
  statusUnderstand: "Tìm hiểu · đang thực hiện",
  statusPrepare: "Chuẩn bị · đang thực hiện",
  statusReady: "Sẵn sàng xem xét", statusNeeds: "Cần xem xét",
  statusAwaiting: "{n} giá trị cần bạn xác nhận",
  statusIssues: "Cần xem xét · {n} mục cần xử lý",
  statusMissingDocs: "Sẵn sàng xem xét · vẫn còn thiếu giấy tờ",
  statusLocked: "Đã khóa · sẵn sàng xem xét",
  errorsMenuTitle: "Những mục cần chú ý",
  errLowConfidence: "Độ tin cậy thấp — hãy kiểm tra giá trị này",
  uploadTitle: "Tải lên giấy tờ của bạn",
  uploadHint:
    "Kéo tệp PDF vào đây hoặc chọn tệp — phiếu lương, thư trợ cấp hoặc thư xác nhận việc làm, bản tóm tắt hồ sơ của bạn.",
  chooseFiles: "Chọn tệp", reading: "Đang đọc giấy tờ của bạn…",
  noDocs: "Chưa có giấy tờ nào. Hãy tải lên một tệp để bắt đầu.",
  checklistTitle: "Danh sách giấy tờ", present: "Đã tải lên", missing: "Vẫn còn thiếu",
  docApplication_summary: "Tóm tắt hồ sơ",
  docPay_stub: "Phiếu lương",
  docEmployment_letter: "Thư xác nhận việc làm",
  docBenefit_letter: "Thư trợ cấp",
  docGig_statement: "Sao kê thu nhập gig",
  docUnknown: "Giấy tờ",
  reviewTitle: "Xác nhận thông tin của bạn",
  reviewHint:
    "Đối chiếu từng giá trị với nguồn của nó, sau đó xác nhận hoặc nhập chỉnh sửa. Chỉ các giá trị đã xác nhận mới được dùng về sau.",
  fieldOf: "Mục {n} / {total}",
  confirm: "Xác nhận", correct: "Sửa", saveCorrection: "Lưu",
  cancel: "Hủy", confidence: "Độ tin cậy",
  stRenterEntered: "Do bạn nhập",
  errNegative: "Lỗi: số tiền không được là số âm.",
  dismiss: "Đóng",
  stExtracted: "Cần bạn kiểm tra", stConfirmed: "Đã xác nhận", stCorrected: "Đã sửa",
  source: "Nguồn",
  page: "Trang {n}",
  openDocument: "Mở tài liệu gốc",
  whyNeeded: "Vì sao cần thông tin này",
  fieldExplainFallback: "{field} — trích xuất từ {doc}.",
  allConfirmed: "Đã xác nhận tất cả giá trị.",
  goUnderstand: "Tiếp tục sang Tìm hiểu",
  quarantineTitle: "Văn bản bị cách ly — đã bỏ qua",
  quarantineHint:
    "Tài liệu này chứa các chỉ dẫn nhắm vào trợ lý. RealDoor bỏ qua các chỉ dẫn nhúng; văn bản chỉ được hiển thị để minh bạch và không bao giờ được dùng làm dữ liệu.",
  understandTitle: "Tìm hiểu thu nhập và quy định",
  incomeCalcTitle: "Thu nhập quy đổi theo năm",
  householdSize: "Số người trong hộ",
  annualizedIncome: "Tổng thu nhập theo năm",
  srcCorroborates: "xác nhận cùng một nguồn — không cộng thêm",
  viewerLabel: "Trình xem tài liệu",
  zoomIn: "Phóng to",
  zoomOut: "Thu nhỏ",
  zoomFit: "Vừa chiều rộng",
  pageOfTotal: "Trang {n} / {total}",
  snapToField: "Đến giá trị",
  previewError: "Không thể hiển thị bản xem trước tài liệu. Hãy dùng liên kết bên dưới để mở bản gốc.",
  sampleQ1: "Giới hạn thu nhập 60% cho hộ bốn người là bao nhiêu?",
  sampleQ2: "Giới hạn thu nhập FY2026 có hiệu lực khi nào?",
  sampleQ3: "Thu nhập định kỳ được quy đổi theo năm như thế nào?",
  sampleQ4: "Khi nào hồ sơ sẵn sàng để xem xét?",
  mathPerPeriod: "Mỗi kỳ",
  mathPeriodsYr: "Số kỳ / năm",
  mathCalc: "Phép tính",
  mathPerYear: "Mỗi năm",
  mathTotal: "Tổng",
  srcPay: "Tiền lương",
  srcBenefit: "Trợ cấp",
  srcGig: "Thu nhập gig",
  aiThinking: "Đang kiểm tra nguồn…",
  aiPrivacy:
    "Quyền riêng tư AI: chỉ gửi các giá trị số đã xác nhận, trạng thái và tham chiếu nguồn — không bao giờ gửi tệp, nội dung tài liệu, tên, địa chỉ hay tên tệp của bạn. Tránh nhập thông tin cá nhân vào câu hỏi.",
  aiFallback: "Trợ lý AI trực tuyến không khả dụng, RealDoor đã dùng phương án dự phòng quy tắc cố định cục bộ.",
  freqWeekly: "hằng tuần", freqBiweekly: "hai tuần một lần", freqSemimonthly: "nửa tháng một lần",
  freqMonthly: "hằng tháng", freqAnnual: "hằng năm",
  threshold60: "Giới hạn thu nhập 60% (FY2026)", comparison: "So sánh",
  cmpBelow: "Bằng hoặc thấp hơn giới hạn", cmpAbove: "Cao hơn giới hạn",
  cmpNone: "Không có ngưỡng cố định cho số người này trong hộ",
  effective: "Hiệu lực từ",
  notDecision: "Điều này so sánh thu nhập của bạn với giới hạn đã công bố — không phải quyết định điều kiện.",
  confirmSizeNote: "Xác nhận số người trong hộ ở bước Hồ sơ để có ngưỡng chính xác.",
  formulaHead: "Cách tính",
  sourcesHead: "Nguồn thu nhập",
  rulesTitle: "Hỏi về các quy định",
  rulesHint: "Câu trả lời chỉ đến từ bộ quy tắc cố định, mỗi câu kèm trích dẫn.",
  askPlaceholder: "vd. Giới hạn 60% cho hộ bốn người là bao nhiêu?",
  ask: "Hỏi",
  tryAsking: "Thử hỏi",
  answerIntro: "Từ bộ quy tắc:",
  aiSources: "Nguồn",
  aiGuideLabel: "Hướng dẫn RealDoor",
  aiCurrentDocument: "Tài liệu hiện tại",
  aiOutcomeAnswered: "Đã trả lời",
  aiOutcomeRefused: "Đã từ chối trả lời",
  aiOutcomeAbstained: "Không trả lời",
  aiOutcomeNeedsConfirmation: "Cần xác nhận",
  aiOutcomeOutOfScope: "Ngoài phạm vi",
  authOfficialHud: "Chính thức · HUD",
  authOfficialFederal: "Chính thức · Liên bang",
  authChallenge: "Quy ước cuộc thi",
  abstain:
    "Tôi chỉ có thể trả lời từ bộ quy tắc cố định và không tìm thấy quy tắc phù hợp. Hãy thử hỏi về giới hạn thu nhập, ngày hiệu lực, cách quy đổi thu nhập theo năm, hoặc mức độ sẵn sàng của hồ sơ.",
  refusal: "RealDoor không thể cho biết bạn có đủ điều kiện hay không, hay bạn sẽ được chấp thuận hoặc bị từ chối — đó là các quyết định của con người. Nó chỉ chuẩn bị, kiểm tra giấy tờ và so sánh thu nhập với một giới hạn đã công bố.",
  prepareTitle: "Chuẩn bị và hoàn tất", readinessTitle: "Mức độ sẵn sàng của hồ sơ",
  verdictNote: "Điều này mô tả mức độ đầy đủ và nhất quán của hồ sơ — không bao giờ là điều kiện.",
  reasonsTitle: "Cần xử lý",
  noReasons: "Mọi thứ đều ổn — hồ sơ đầy đủ và nhất quán.",
  prepareIntro:
    "Kiểm tra biên nhận bên dưới — sửa những mục được đánh dấu đỏ, sau đó lưu thành PDF hoặc tải gói dữ liệu.",
  rcTitle_PAY_STUB_TOTAL_CONFLICT: "Tổng số trên phiếu lương không khớp",
  rcTitle_GIG_INCOME_UNCORROBORATED: "Thu nhập tự do chưa có bằng chứng",
  rcTitle_EMPLOYMENT_LETTER_EXPIRED: "Thư xác nhận việc làm đã hết hạn",
  rcTitle_UNCONFIRMED_FIELDS: "Các trường chưa được xác nhận",
  rcTitle_LOW_CONFIDENCE_FIELDS: "Các trường có độ tin cậy thấp",
  rcTitle_MISSING_REQUIRED_DOCUMENT: "Thiếu tài liệu được khuyến nghị",
  rc_PAY_STUB_TOTAL_CONFLICT: "Tổng lương ghi trên một phiếu lương không khớp với đơn giá theo giờ × số giờ.",
  rc_GIG_INCOME_UNCORROBORATED: "Thu nhập gig đã được tính nhưng cần thêm chứng thực.",
  rc_EMPLOYMENT_LETTER_EXPIRED: "Một thư xác nhận việc làm cũ hơn khung hiệu lực 60 ngày.",
  rc_UNCONFIRMED_FIELDS: "Một số mục vẫn cần bạn xác nhận.",
  rc_LOW_CONFIDENCE_FIELDS: "Một số mục được trích xuất với độ tin cậy thấp.",
  rc_BENEFIT_LETTER_EXPIRED: "Một thư trợ cấp đã quá cửa sổ hiệu lực 60 ngày.",
  rc_PAY_STUB_EXPIRED: "Một phiếu lương đã quá cửa sổ hiệu lực 60 ngày.",
  rc_GIG_STATEMENT_EXPIRED: "Một bảng kê thu nhập gig đã quá cửa sổ hiệu lực 60 ngày.",
  rc_EMPLOYMENT_RATE_CONFLICT: "Thư của chủ lao động ghi đơn giá giờ khác với phiếu lương.",
  rc_MISSING_HOUSEHOLD_SIZE: "Không có số người trong hộ được ghi nhận — không thể áp dụng bảng ngưỡng cố định.",
  rc_MISSING_INCOME_EVIDENCE: "Không tìm thấy bằng chứng thu nhập định kỳ được ghi nhận.",
  rc_NO_FROZEN_THRESHOLD: "Quy mô hộ nằm ngoài bảng cố định 1–8; không có ngưỡng cố định.",
  rc_UNVERIFIED_INCOME_CLAIM: "Một khoản thu nhập tự khai không có bằng chứng hỗ trợ và không được tính.",
  rcTitle_BENEFIT_LETTER_EXPIRED: "Thư trợ cấp hết hạn",
  rcTitle_PAY_STUB_EXPIRED: "Phiếu lương hết hạn",
  rcTitle_GIG_STATEMENT_EXPIRED: "Bảng kê gig hết hạn",
  rcTitle_EMPLOYMENT_RATE_CONFLICT: "Xung đột đơn giá giờ",
  rcTitle_MISSING_HOUSEHOLD_SIZE: "Thiếu số người trong hộ",
  rcTitle_MISSING_INCOME_EVIDENCE: "Thiếu bằng chứng thu nhập",
  rcTitle_NO_FROZEN_THRESHOLD: "Không có ngưỡng cố định",
  rcTitle_UNVERIFIED_INCOME_CLAIM: "Thu nhập tự khai chưa xác minh",
  rc_MISSING_REQUIRED_DOCUMENT: "Một giấy tờ được khuyến nghị vẫn chưa được tải lên.",
  editBtn: "Chỉnh sửa thông tin", downloadBtn: "Tải gói hồ sơ",
  deleteBtn: "Xóa phiên", lockBtn: "Xác nhận — khóa là sẵn sàng xem xét",
  unlockBtn: "Mở khóa để chỉnh sửa",
  lockedNote: "Đã khóa là sẵn sàng xem xét. Bạn có thể mở khóa để chỉnh sửa.",
  deleteConfirm: "Xóa mọi thứ trong phiên này? Giấy tờ, các giá trị đã trích xuất và biên nhận này sẽ bị xóa.",
  deletedProof: "Đã xóa phiên. Đã gỡ {docs} giấy tờ và {fields} giá trị lúc {at}.",
  fieldsConfirmed: "Đã xác nhận {n} / {total} mục",
  receiptTitle: "Biên nhận mức độ sẵn sàng của bạn",
  receiptPrint: "Lưu biên nhận dưới dạng PDF",
  rawShow: "Xem dữ liệu thô", rawHide: "Ẩn dữ liệu thô",
  sampleWord: "BẢN MẪU",
  sampleBanner:
    "Đây là tài liệu BẢN MẪU được tạo từ dữ liệu phiên của bạn. Nó không phải là biểu mẫu chính thức và không bao giờ được gửi đi đâu.",
  receiptKicker: "Giấy tờ nhà ở giá phải chăng · Boston · BẢN MẪU",
  receiptDocTitle: "Biên nhận mức độ sẵn sàng của hồ sơ",
  receiptGenerated: "Tạo ngày {date}",
  receiptFileLabel: "Hồ sơ",
  receiptSecDocs: "Giấy tờ đã cung cấp",
  receiptSecIncome: "Tính toán thu nhập",
  receiptSecReadiness: "Mức độ sẵn sàng của hồ sơ",
  receiptEditNote: "Các chỉnh sửa tại đây sẽ cập nhật toàn bộ hồ sơ của bạn ngay lập tức.",
  invalidAmount: "Nhập một số không âm, ví dụ 1250.00.",
  receiptFooter:
    "RealDoor chuẩn bị bản tóm tắt này để hỗ trợ người xét duyệt. Nó không thể cho bạn biết bạn có đủ điều kiện hay không — mức độ sẵn sàng chỉ mô tả giấy tờ. Chỉ để tải xuống: biên nhận này không bao giờ được truyền đi.",
};

const COPIES: Record<Language, Copy> = { en, es, zh, tl, vi };

// Localized labels for parsed-document field keys (receipt rows, field review).
// English is complete; other languages fall back en → humanized key.
const FIELD_LABELS_EN: Record<string, string> = {
  person_name: "Person name",
  household_size: "Household size",
  address: "Address",
  application_date: "Application date",
  declared_income: "Declared income",
  pay_date: "Pay date",
  pay_frequency: "Pay frequency",
  pay_period_start: "Pay period start",
  pay_period_end: "Pay period end",
  regular_hours: "Regular hours",
  hourly_rate: "Hourly rate",
  gross_pay: "Gross pay",
  net_pay: "Net pay",
  document_date: "Document date",
  weekly_hours: "Weekly hours",
  benefit_frequency: "Benefit frequency",
  benefit_amount: "Benefit amount",
  weekly_benefit: "Weekly benefit",
  biweekly_benefit: "Biweekly benefit",
  semimonthly_benefit: "Semimonthly benefit",
  monthly_benefit: "Monthly benefit",
  annual_benefit: "Annual benefit",
  statement_month: "Statement month",
  gross_receipts: "Gross receipts",
  platform_fees: "Platform fees",
};

export const FIELD_LABELS: Record<Language, Record<string, string>> = {
  en: FIELD_LABELS_EN,
  es: {
    person_name: "Nombre", household_size: "Tamaño del hogar", address: "Dirección",
    application_date: "Fecha de solicitud", declared_income: "Ingresos declarados",
    pay_date: "Fecha de pago", pay_frequency: "Frecuencia de pago",
    pay_period_start: "Inicio del período de pago", pay_period_end: "Fin del período de pago",
    regular_hours: "Horas regulares", hourly_rate: "Tarifa por hora",
    gross_pay: "Pago bruto", net_pay: "Pago neto", document_date: "Fecha del documento",
    weekly_hours: "Horas semanales", benefit_frequency: "Frecuencia del beneficio",
    benefit_amount: "Monto del beneficio", weekly_benefit: "Beneficio semanal",
    biweekly_benefit: "Beneficio quincenal", semimonthly_benefit: "Beneficio semimensual",
    monthly_benefit: "Beneficio mensual", annual_benefit: "Beneficio anual",
    statement_month: "Mes del estado", gross_receipts: "Ingresos brutos",
    platform_fees: "Comisiones de la plataforma",
  },
  zh: {
    person_name: "姓名", household_size: "家庭人数", address: "地址",
    application_date: "申请日期", declared_income: "申报收入",
    pay_date: "发薪日期", pay_frequency: "发薪频率",
    pay_period_start: "工资周期开始", pay_period_end: "工资周期结束",
    regular_hours: "正常工时", hourly_rate: "时薪",
    gross_pay: "总工资", net_pay: "实发工资", document_date: "文件日期",
    weekly_hours: "每周工时", benefit_frequency: "福利发放频率",
    benefit_amount: "福利金额", weekly_benefit: "每周福利",
    biweekly_benefit: "双周福利", semimonthly_benefit: "半月福利",
    monthly_benefit: "每月福利", annual_benefit: "年度福利",
    statement_month: "报表月份", gross_receipts: "总收入", platform_fees: "平台费用",
  },
  tl: {
    person_name: "Pangalan", household_size: "Laki ng sambahayan", address: "Address",
    application_date: "Petsa ng aplikasyon", declared_income: "Idineklarang kita",
    pay_date: "Petsa ng sahod", pay_frequency: "Dalas ng sahod",
    pay_period_start: "Simula ng panahon ng sahod", pay_period_end: "Katapusan ng panahon ng sahod",
    regular_hours: "Regular na oras", hourly_rate: "Singil kada oras",
    gross_pay: "Gross na sahod", net_pay: "Net na sahod", document_date: "Petsa ng dokumento",
    weekly_hours: "Oras kada linggo", benefit_frequency: "Dalas ng benepisyo",
    benefit_amount: "Halaga ng benepisyo", weekly_benefit: "Lingguhang benepisyo",
    biweekly_benefit: "Benepisyo kada dalawang linggo", semimonthly_benefit: "Benepisyo kada kalahating buwan",
    monthly_benefit: "Buwanang benepisyo", annual_benefit: "Taunang benepisyo",
    statement_month: "Buwan ng ulat", gross_receipts: "Gross na kita", platform_fees: "Bayarin sa platform",
  },
  vi: {
    person_name: "Họ tên", household_size: "Quy mô hộ gia đình", address: "Địa chỉ",
    application_date: "Ngày nộp đơn", declared_income: "Thu nhập kê khai",
    pay_date: "Ngày trả lương", pay_frequency: "Tần suất trả lương",
    pay_period_start: "Bắt đầu kỳ lương", pay_period_end: "Kết thúc kỳ lương",
    regular_hours: "Số giờ chuẩn", hourly_rate: "Lương theo giờ",
    gross_pay: "Lương gộp", net_pay: "Lương thực nhận", document_date: "Ngày của tài liệu",
    weekly_hours: "Số giờ mỗi tuần", benefit_frequency: "Tần suất trợ cấp",
    benefit_amount: "Số tiền trợ cấp", weekly_benefit: "Trợ cấp hằng tuần",
    biweekly_benefit: "Trợ cấp hai tuần", semimonthly_benefit: "Trợ cấp nửa tháng",
    monthly_benefit: "Trợ cấp hằng tháng", annual_benefit: "Trợ cấp hằng năm",
    statement_month: "Tháng sao kê", gross_receipts: "Tổng doanh thu", platform_fees: "Phí nền tảng",
  },
};

export function useCopy(): Copy {
  const { language } = useI18n();
  return COPIES[language];
}

export function fmt(template: string, vars: Record<string, string | number>): string {
  return template.replace(/\{(\w+)\}/g, (_, k) => String(vars[k] ?? `{${k}}`));
}
