create table if not exists public.ai_request_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  request_id uuid not null unique,
  mode text not null check (mode in ('general', 'personalized')),
  outcome text not null check (outcome in ('answered', 'refused', 'abstained', 'needs_confirmation')),
  policy_code text not null,
  rule_ids text[] not null default '{}',
  provider text not null,
  model text not null,
  prompt_version text not null,
  corpus_version text not null,
  app_guide_version text not null,
  input_tokens integer,
  output_tokens integer,
  latency_ms integer not null check (latency_ms >= 0),
  context_included boolean not null default false,
  created_at timestamptz not null default now()
);

comment on table public.ai_request_events is
  'Metadata-only audit and rate-limit ledger. Never store prompts, responses, documents, PII, or financial values.';

create index if not exists ai_request_events_user_created_idx
  on public.ai_request_events (user_id, created_at desc);

alter table public.ai_request_events enable row level security;

create policy "No browser access to AI audit"
on public.ai_request_events
for all
to anon, authenticated
using (false)
with check (false);

revoke all on table public.ai_request_events from anon, authenticated;
grant select, insert, delete on table public.ai_request_events to service_role;
grant usage, select on sequence public.ai_request_events_id_seq to service_role;
